### ISSUE TITLE
Informative error messages: Add line numbers

### ISSUE THREAD

**Issue by traversaro** [pantor/inja#10]
Hi @pantor , thanks for the great library! 

I am trying it for a  ~100 lines template, and I am experiencing errors such as:
~~~
 what():  Unknown function in renderer.
~~~
or
~~~
 what(): Unknown loop statement.
~~~

Do you think there is a way to enrich this error with some information that would help to debug the problem, for example the line number in the original template file? Thanks in advance.

**Comment by pantor** [comment]
That's true, the current error messages are really a drawback of this library. I think line numbers are a good start, so I'll have a look at this later 👍

**Comment by ludekvodicka** [comment]
Hi, better error messages would be great!

But also would be great to do more checks before calling Json library. For example when eval_expression() is trying to get non-existing values via following command

`const json result = data[json::json_pointer(input)];`

Json library asserted in this code:

    const_reference operator[](const typename object_t::key_type& key) const
    {
        // const operator[] only works for objects
        if (JSON_LIKELY(is_object()))
        {
            assert(m_value.object->find(key) != m_value.object->end());
            return m_value.object->find(key)->second;
        }

        JSON_THROW(type_error::create(305, "cannot use operator[] with " + std::string(type_name())));
    }


Unfortunately, such assertion isn't possible to catch via Exception handler and cause the application crash.

**Comment by pantor** [comment]
The latest commit already uses `at` in the `eval_expression` function. So that specific check should be solved. There are still a few problems with the CI and error checking, so I need to work on that first...

**Comment by ludekvodicka** [comment]
Perfect. I already updated it. 

I wasn't sure if you're interested in PRs so I'm really grateful you merged. Now I don't do that manually on every new version ;-).

Thanks for good work!

**Comment by pantor** [comment]
This is now implemented for parser errors.

**Comment by pantor** [comment]
With the latest commit, this is now implemented for render erros as well.
