### ISSUE TITLE
Using both nlohmann json and inja as git submodule

### ISSUE THREAD

**Issue by neel** [pantor/inja#103]
I am already using `nlohmann json` as a git submodule in `PROJECT_ROOT/dependencies`. Now I want to use inja under the same `PROJECT_ROOT/dependencies` directory as a git submodule. 

In the CMakeLists.txt file under the dependencies directory I have 

```
SET(JSON_BuildTests OFF CACHE INTERNAL "")
add_subdirectory(json)
add_subdirectory(inja)
```

`cmake ..` complains that the target `nlohmann_json` already exists

```
-- Using the single-header code from /home/neel/Projects/byakaran/dependencies/json/single_include/
CMake Error at dependencies/inja/CMakeLists.txt:47 (add_library):
  add_library cannot create target "nlohmann_json" because another target
  with the same name already exists.  The existing target is an interface
  library created in source directory
```

If I set `INJA_USE_EMBEDDED_JSON` to `OFF` then also it wont work because inja `CMakeList.txt` tries to `find_package(nlohmann_json REQUIRED)` which fails because `nlohmann_json` is not installed in my system. It is added as a submodule.

What is the solution ?

**Comment by pantor** [comment]
I added a possible fix for that with the latest commit, I hope that works for you? If you turn `INJA_USE_EMBEDDED_JSON` off, cmake now checks if the target `nlohmann_json` already exists and reuses that if so.

**Comment by neel** [comment]
Worked with 
```
SET(INJA_USE_EMBEDDED_JSON OFF)
add_subdirectory(inja)
```
However I am getting the following CMake error on the first build

```
CMake Warning (dev) at dependencies/inja/CMakeLists.txt:7 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'INJA_USE_EMBEDDED_JSON'.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

But once I rebuild (without cleaning) it compiles fine.
