### ISSUE TITLE
Exception occuring if the replaceable hierarchy not present in string passed to render method.

### ISSUE THREAD

**Issue by code-blooded245** [pantor/inja#106]
std::string data1 = "{\"test\":\"%%abc.def%%\"}";
json data2;      
data2["abc"]["xyz"] = "testData";
cout << env.render(data1, data2) << endl;

what I was expecting is whatever data can be replaced from the json data2 will be replaced and whatever cannot be will be kept empty or kept as is in the returned string but I am getting an exception [inja.exception.render_error] variable 'abc.def' not found and the string which I am sending is destroyed. Please help, @pantor

**Comment by ashwin279** [comment]
gentle reminder.

**Comment by code-blooded245** [comment]
any updates?

**Comment by pantor** [comment]
At the moment, this is the desired behavior. If you want to an empty placeholder if data is not found, you can use:
```c++
std::string template = R"({"test":"%% default(abc.def, "") %%"})";

json data;
data["abc"]["xyz"] = "testData";
std::cout << env.render(template, data) << std::endl;
```

**Comment by code-blooded245** [comment]
okay thanks, will update on if I face any issue regarding this.
