### ISSUE TITLE
Various items in the README file

### ISSUE THREAD

**Issue by davidschachter** [pantor/inja#111]
1. In the README file, the word "ommitted" should have one m.
2. In the README file, in the section "Includes," there are missing quotes around the strings. And the quotes around "footer.txt" in the first example and "footer" in the second example should be escaped with backslashes.
3. In the same section, the second example doesn't work for me. The word "footer" is interpreted as a filename, not as a key to a parsed template.

**Comment by pantor** [comment]
Thanks!
