### ISSUE TITLE
Automatic monitoring of changes to template files?

### ISSUE THREAD

**Issue by davidschachter** [pantor/inja#112]
A neat feature would be an option for Inja to monitor template files for changes and reparse the in-memory representation when the template file changes. An acceptable alternative would be a callback I can set into my code, called before a template is rendered, such that the callback could determine if the parsed template is out-of-date and fix the problem.

**Comment by thomastrapp** [comment]
I think this would be best solved outside of inja.
For example, on linux you can use `inotify` to watch a file or directory (recursively) for changes. If a file is changed on disk you can then reparse the template. If the template was already included in an `inja::Environment`, you can overwrite the old version of the template by calling `Environment::include_template` again.

**Comment by pantor** [comment]
As @thomastrapp said, I also think that this should be handled outside of inja. So I'll close this issue as out of scope, but thanks for your input regardless!
