### ISSUE TITLE
Debug messages

### ISSUE THREAD

**Issue by davidschachter** [pantor/inja#113]
I added printouts to Inja in various places to understand why it couldn't find my template files. It would be helpful if Inja could be told to "open itself up" for debugging and for performance analysis, printing information about what it is doing. This would include finding files, parsing files, and rendering templates. Debug messages should include a precise timestamp, so I can understand the impact on performance of my design decisions for templates.

**Comment by pantor** [comment]
With the latest commit, inja now throws a helpful error if an included template is not found. Also render errors now give a precise location in the file. I hope that this solves most of your issue.

**Comment by davidschachter** [comment]
Thank you!
