### ISSUE TITLE
Could you improve the performance of inja?

### ISSUE THREAD

**Issue by qicosmos** [pantor/inja#115]
Hi all,
I tested the performance of inja, i found render is much more slower than parse.
```
env.parse(str); //166ms
env.render(str, t); //1216ms
```
so could you improve the performance of render?

**Comment by davidschachter** [comment]
@qicosmos, what template are you testing with? What data is being substituted in (in the variable "t"?) And what are the characteristics of the machine you are testing with?

**Comment by qicosmos** [comment]
This is the test code:
```
void test() {
	json t;
	t["title"] = "Sample Site";
	json xs;
	xs.push_back({
						 { "enable", true },
						 { "url", "http://example.com" },
						 { "value", "Example" },
		});
	xs.push_back({
						 { "enable", false },
						 { "url", "undefined" },
						 { "value", "Test" },
		});
	xs.push_back({
						 { "enable", true },
						 { "url", "http://google.com" },
						 { "value", "Google" },
		});

	t["xs"] = xs;

	nonstd::string_view str = "a{% for x in xs %}\n"
		"{%if x.enable %}"
		"{{x.url}}"
		"{% endif %}"
		"{% endfor %}b\n";

	using namespace std;
	for (int j = 0; j < 5; ++j) {
		auto last = chrono::system_clock::now();
		for (int i = 0; i < 100000; ++i) {
			env.parse(str);
			//env.render(str, t);
		}
		auto now = chrono::system_clock::now();
		auto tm = chrono::duration_cast<chrono::milliseconds>(now - last).count();
		std::cout << tm << "\n";
	}
}
```
8 core cpu 3.6G RAM 32G

**Comment by victordk13** [comment]
@qicosmos Is your measured time (166/1216ms) per 100000 iterations (as in the test code)?

**Comment by qicosmos** [comment]
yes, (166/1216ms) per 100000.
I measured five times as the code show, the results are close every time.

**Comment by qicosmos** [comment]
I guess the nlohmann json slow down the efficiency, there are so many copies when construct the json object.
Maybe std::any or variant are better choise than nlohmann json.

**Comment by flexferrum** [comment]
> Maybe std::any or variant is better choice than nlohmann json, although nlohmann json is more easier to use.

It's not only about value representation but about internal values storage as well. I suppose, nlohmann json isn't a good choice for the fast storage.

**Comment by pantor** [comment]
For now, performance improvements are not our major focus. We did improve it with inja version 2.0, and could further increase the performance by switching from nlohmann/json. But of course - always feel free to make a PR! 😉
