### ISSUE TITLE
Use const json& rather than "json" in  std::function<json(Parsed::Arguments, json)>> ?

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#12]
Hi,

just updating my code to use your latest callbacks and I have a question. Wouldn't be bettter to pass json data as const reference instead of copying it on every callback?

This means use

`std::map<std::string, std::function<json(Parsed::Arguments, const json&)>> map_callbacks;`
instead of
`std::map<std::string, std::function<json(Parsed::Arguments, json)>> map_callbacks;`

and

`env.add_callback("double", 1, [&env](inja::Parsed::Arguments args, const json &data) {..}`
instead
`env.add_callback("double", 1, [&env](inja::Parsed::Arguments args, json data) {..}`

and here

`void add_callback(std::string name, int number_arguments, std::function<json(Parsed::Arguments, const json&)> callback) {`
instead
`void add_callback(std::string name, int number_arguments, std::function<json(Parsed::Arguments, json)> callback) {...`

Ludek

**Comment by ludekvodicka** [comment]
The same here:

```
	T get_argument(Parsed::Arguments args, int index, json data) {
		return renderer.eval_expression<T>(args[index], data);
	}

```

when evaluating expression json is again copied instead of passed as is.

The same is here:
`T eval_expression(const Parsed::ElementExpression& element, const json &data) ...`

and here
`json eval_function(const Parsed::ElementExpression& element, const json& data) {`


I will create another PR with these fixes.

**Comment by pantor** [comment]
Thanks!

**Comment by ludekvodicka** [comment]
I just found few more const& optimizations. PR is ready
