### ISSUE TITLE
Running example error

### ISSUE THREAD

**Issue by FONQRI** [pantor/inja#121]
Hello
I'm trying to use below example:
```c++
json data;
data["neighbour"] = "behnam";
inja::Template content_template = env.parse("Hello {{ neighbour }}!");
env.include_template("content", content_template);
std::clog << render("Content: {% include \"content\" %}", data) << std::endl;
```

But i'm getting below error : 
```c++
terminate called after throwing an instance of 'std::runtime_error'
  what():  [inja.exception.file_error] failed accessing file at 'content'
```

**Comment by thomastrapp** [comment]
The example is wrong :)
`inja::render` does not have access to your `inja::Environment`, but `inja::Environment::render` does.

Call `env.render`, like this:

> ```c++
> std::clog << env.render("Content: {% include \"content\" %}", data) << std::endl;
> ```

**Comment by FONQRI** [comment]
Thanks a lot.
