### ISSUE TITLE
Support for Bytecode::Op::At in release version

### ISSUE THREAD

**Issue by mauricelos** [pantor/inja#129]
The API documentation is showing an example of the range function for the inja template:
```
render("{% for i in range(3) %}{{ at(guests, i) }} {% endfor %}", data); // "Jeff Tom Patrick "
```
Unfortunately the "at" feature (Bytecode::Op::At) is not included in the release 2.1. Would it be possible to create a new release which has the feature "at" as mentioned in the official documentation?

Here is an example of how we want to use this "at" feature, if you know any alternative to how to solve this without "at", that would be appreciated as well:
```
data["guests"] = {"Jeff", "Tom", "Patrick"};
data["ages"] = {"25", "24", "52"};
render_to(std::cout, R"(Guest List:
## for i in range(3)
{{ loop.index1 }}: {{ at(guests, i) }} {{at(ages, i)}}
## endfor )", data);
```
```
Output
Guest List:
1: Jeff 25
2: Tom 24
3: Patrick 52
```

**Comment by pantor** [comment]
Version 2.2 is now published!
