### ISSUE TITLE
Add Inja support to Nift

### ISSUE THREAD

**Issue by n-ham** [pantor/inja#130]
I make the world's fastest website generator with C++ called Nift (https://nift.cc). I've just come across Inja and added it to the recommended template languages on the page https://www.nift.cc/docs/template_languages.html. It should be possible to already write programs to use inja and write the output to file, which Nift can then inject and parse with its own template language when building, or even better use Nift to build pages to inja format then have post build scripts to run programs to convert the built page from inja to html or something like that. 

However I think with perhaps a bit of help from you folks we could come up with an even better (ie. faster and more convenient) solution that allows the use of Inja in content/template files being built with Nift. Is this something you would be interested in collaborating on?

**Comment by pantor** [comment]
Hi, this is really great to see! Unfortunately, I don't have much time to spend on inja and there are some fundamental issues (like #138) which should be addressed first and foremost.

Beside that, what are your interests and plans?
