### ISSUE TITLE
Question: count the number of variables before rendering

### ISSUE THREAD

**Issue by 3p3r** [pantor/inja#132]
Hi! Is there a way to count the number of variables before reducing templates? For example if I have the following template:
```
sample template {{ var1 }} {{ var2 }} {{ max([var3, var4]) }}
```
is there an API call that returns 4 (count of all unrednered variables).

**Comment by 3p3r** [comment]
Currently, I am doing something like this:
```
const auto bytecodes = env.parse(template).bytecodes;
auto variable_count = std::count_if(bytecodes.cbegin(), bytecodes.cend(), [](const inja::Bytecode &bytecode) {
  return bytecode.op == inja::Bytecode::Op::PrintValue;
});
```
but that does not seem like to include variables in function calls

**Comment by pantor** [comment]
With the latest commit, the template class has a `count_variables()` method that should address this issue.
