### ISSUE TITLE
set_lstrip_blocks/env.set_trim_blocks are broken?

### ISSUE THREAD

**Issue by godexsoft** [pantor/inja#136]
Hi, I tried both master and v2.2.0 and the result seems to be the same:

1) The documentation is saying 
```
env.set_lstrip(true);
env.set_trim(true);
```
but the actual code is 
```
env.set_lstrip_blocks(true);
env.set_trim_blocks(true);
```

2) More importantly however.. it has no effect on my output. 

Thanks

**Comment by pantor** [comment]
I've fixed the Readme and added further tests to make sure that they are working fine!

Moreover, I've added more fainegrained whitespace control using `{%-`, `{%+`, and `-%}` for statement blocks.
