### ISSUE TITLE
Error in Tutorial for Statements

### ISSUE THREAD

**Issue by siddhartha-crypto** [pantor/inja#137]
In the tutorial, we have the following code.

```
{c++}
// Combining loops and line statements
render(R"(Guest List:
## for guest in guests
    {{ loop.index1 }}: {{ guest }}
## endfor )", data)
/* Guest List:
    1: Jeff
    2: Tom
    3: Patrick */`
```

I tried this just now while learning Inja and the `##` statements do not work properly. 

The project compiles and executes properly, but when the above statement is reached, the following error is outputted.

```
terminate called after throwing an in
stance of 'std::runtime_error'
  what():  [inja.exception.render_err
or] variable 'loop.index1' not found
```

I was able to solve the problem as follows, verifying that the structure should otherwise work, with the exception of the `##` specifiers.

```
    string str;
    str = render(R"(Guest List:
    {% for guest in guests %}
        {{ loop.index1 }}: {{ guest }}
    {% endfor %} )", data);

    cout << str << endl;
```

**Comment by thomastrapp** [comment]
Line statements have to be placed at the start of a line.

For example, this will work:
```C++
inja::render(
    R"(Guest List:
## for guest in guests
  {{ loop.index1 }}: {{ guest }}
## endfor )", data)
```

But this will not:
```C++
inja::render(
    R"(Guest List:
    ## for guest in guests
      {{ loop.index1 }}: {{ guest }}
    ## endfor )", data)
```
Notice the indentation before "##". This causes the line statement to not be recognized and taken as literal text.

**Comment by pantor** [comment]
I've added a sentence in the readme that line statements should be used without indentation.

**Comment by siddhartha-crypto** [comment]
Thank you.
