### ISSUE TITLE
Having trouble with more than one "or" in statement

### ISSUE THREAD

**Issue by erictorgerson** [pantor/inja#138]
## if not loop/is_last or exists("Pump_Stop_Event") or exists("Other_Event_Crew") or exists("Image_Quality")

the line above fails to parse with "[inja.exception.parser_error] (at 102:54) expected line statement close, got 'or'

seems to work fine with a single "or."  Perhaps I am missing something here?

**Comment by tstraus** [comment]
I'm seeing the same thing.

**Comment by pantor** [comment]
Yeah, this is indeed a problem.

Inja doesn't use a proper AST at the moment, but this takes a lot of effort to rewrite. So I'll keep this issue open for version 3.0. 😉

**Comment by pantor** [comment]
I'll close this issue in favor of #147. Thanks for reporting!

**Comment by erictorgerson** [comment]
Sounds good - thanks!

Eric Torgerson
907 209 3838

**Comment by tstraus** [comment]
Awesome, this is such a cool project BTW
