### ISSUE TITLE
Json dependency is installed in weird place.

### ISSUE THREAD

**Issue by stilgarpl** [pantor/inja#139]
I've build and installed this library from sources. I didn't have nlohmann/json.hpp installed at the time, and when I tried to use it, it failed, because inja.hpp includes #include <nlohmann/json.hpp>. It also installs it to /usr/local/include/inja/json/include/nlohmann (notice nested "include/" path for json). Of course it can't find it in there, so there is an error during compilation. 

So, either this path should be fixed so that json.hpp is installed alongside inja in place where it can be found or it should be specified as required dependency in CMakeLists.txt and not installed with inja. 

Steps to reproduce:
1. Clone the repo on a system that doesn't have nlohmann/json.hpp installed. 
2. Configure cmake, build, install. 
3. inja.hpp can't find  <nlohmann/json.hpp>

**Comment by pantor** [comment]
This should be fixed with the latest commit. nlohmann/json is now installed into `/usr/local/include/nlohmann`.
