### ISSUE TITLE
Add ability to disable includes

### ISSUE THREAD

**Issue by ArntWork** [pantor/inja#141]
Hi, in an environment where user input is included in (or is the entire) template, I would like to disable includes as a defense-in-depth measure (to prevent file content access via this method).
I propose adding a switch to the environment to do that.
env.disableInclude();
If anything else can access files on disk, I would want to block that too and maybe something like:
env.blockLocalfileaccess();

**Comment by pantor** [comment]
With the latest commit, you can set `env.set_search_included_templates_in_files(false);` on the `Environment` class to disable local file access.
