### ISSUE TITLE
Extend callbacks to be able to proceed variable number of params

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#15]
Hi,

would be great if add_callback() method allow adding functions with "up-to" number of params, not necessary with the equal number.

After that, it would be possible to do following logic:

	inja::Environment env = inja::Environment();
	env.add_callback("test", 2, [&env](inja::Parsed::Arguments args, const nlohmann::json &data) {
		if (env.get_arguments_count() == 2)
		{
			int n1 = env.get_argument<int>(args, 0, data);
			int n2 = env.get_argument<int>(args, 1, data);
			return n1 + n2;
		}
		else if (env.get_arguments_count() == 1)
		{
			int n1 = env.get_argument<int>(args, 0, data);
			return n1;
		}
		else if (env.get_arguments_count() == 0)
		{
			return 42;
		}

	});

	nlohmann::json data;
	InjaStringType res = env.render("{{ test(1,2) }}", data);
	TEST_CHECK_EQUAL(res, "3");

	res = env.render("{{ test(2) }}", data);
	TEST_CHECK_EQUAL(res, "2");

	res = env.render("{{ test() }}", data);
	TEST_CHECK_EQUAL(res, "42");

**Comment by ludekvodicka** [comment]
I'm trying to extend add_callback for variable number of params. I just found few problems:

= Existing regex `function\((.*),(.*)\)` is valid for functions with more than required params. For example fce(1,2,3). returns Group A=1,2 and GroupB=3

the better form is function\(([^,]*),([^,]*)\) This will capture exactly two params.

I also tried to update regex for variable number of params with upper limit passed to template. Curerntly the best regex seems to be

x(?:([^,]*),){0,1}(?:([^,]*),){0,1}(?:([^,]*)){0,1}

I will try to implement it and let you know

**Comment by ludekvodicka** [comment]
I managed to make an implementation for a different number of parameters but now few of your functions doesn't work ;-).

The problem is that current implementation is using fact that for single parameter there is no detection for "," so also parsing "[1,2,3]" works correctly.

But such parser have also some troubles for parsing multiple string parameters when one will contain character ",".  For example test("Hi,there","hello") will parse three parameters instead of two.

The only solution seems to be a little "hack" to parse functions with one parameter by old way and functions with more than one parameter via new way.

What do you think about it?

**Comment by ludekvodicka** [comment]
It's implemented (but it was messy...) ;-).

Implemented variable number of parameters
-  extended function "function_regex" to pass minimum and maximum parameters. if minimum=maximum, all params are required, if minimum = 0, all params are optional.....
- for single parameter there is different regex (created by the same function_regex function) to allo read sort([1,2,3]) as one parameter 
- extended Match to test if group is valid, so only valid params are filled to params vector
- new function arguments_count to test number of arguments passed to callback
-Also created new unit tests to test this feature.

please check my PR.  In case you agree, it will be necessary to update few of your unit tests where you're testing created regex (create-regex-functions for example). I leave this as is so you can compare regexs.

**Comment by pantor** [comment]
I've now added the possibility to add multiple callbacks with the same name but different number of arguments. So your first example could be written like:
```
inja::Environment env = inja::Environment();
env.add_callback("test", 2, [&env](inja::Parsed::Arguments args, const nlohmann::json &data) {
	int n1 = env.get_argument(args, 0, data);
	int n2 = env.get_argument(args, 1, data);
	return n1 + n2;
});
env.add_callback("test", 1, [&env](inja::Parsed::Arguments args, const nlohmann::json &data) {
	return env.get_argument<int>(args, 0, data);
});
env.add_callback("test", 0, [&env](inja::Parsed::Arguments args, const nlohmann::json &data) {
	return 42;
});
```

You are right, the expression parser is not really usable (and correct) for complex applications. In the long-term, the parser should output a real AST. Then, we can add more syntactic sugar like default parameters.
