### ISSUE TITLE
Break in 3.0 of iterating over array

### ISSUE THREAD

**Issue by rroelke** [pantor/inja#156]
[inja-issue.tar.gz](https://github.com/pantor/inja/files/5011342/inja-issue.tar.gz)
Template ```sample.c.template```:
```
#include <stdio.h>

int main(int argc, char **argv) {
## for val in values
    printf("%d\n", {{val}});
## endfor
    return 0;
}
```

JSON data in ```sample.json```:
```
{
    "values" : [
        0, 1, 2, 3, 4, 5
    ]
}
```

I have created an executable ```jsonproc``` which just instantiates the template.

Output for inja 2.2:
```
$  /tmp/inja/test $ make
make -C ../ jsonproc
make[1]: Entering directory '/tmp/inja'
g++ -Wall -std=c++11 -O2 -I . jsonproc.cpp -o jsonproc 
make[1]: Leaving directory '/tmp/inja'
../jsonproc sample.json sample.c.template sample.c
cc -O0 -g -Wall sample.c -o sample

$ /tmp/inja/test $ ./sample 
0
1
2
3
4
5
```

Output using inja 3.0:
```
$ tmp/inja/test $ make
make -C ../ jsonproc
make[1]: Entering directory '/tmp/inja'
g++ -Wall -std=c++11 -O2 -I . jsonproc.cpp -o jsonproc 
make[1]: Leaving directory '/tmp/inja'
../jsonproc sample.json sample.c.template sample.c
JSONPROC_ERROR: [inja.exception.render_error] (at 6:22) variable 'val' not found
make: *** [Makefile:24: sample.c] Error 1
```

I've attached an archive containing the repro.

**Comment by pantor** [comment]
Inja 3.0 is tested with nlohmann/json version **3.8**, which fixes this problem.

However, I don't think this is currently stated somewhere, so we should change that...

**Comment by pantor** [comment]
I've now added it to the realease notes as a breaking change. I'm not sure if there should be a hard check for that in the code?

**Comment by rroelke** [comment]
The release notes or a version check would be enough to have stopped this issue from being created, a hard check will stop others from stumbling into this with more certainty.
Thanks for the fast response!
