### ISSUE TITLE
Pointer not initialised. 

### ISSUE THREAD

**Issue by rafadesu** [pantor/inja#161]
https://github.com/pantor/inja/blob/a138be46b6b8d4bad161b540a910b877fcab40ec/include/inja/node.hpp#L292

There are some cases in which members are not initialised. This maybe be a bit concerning for the cases where the member is a raw pointer.

Our static analyser pointed this out.

**Comment by pantor** [comment]
This should be fixed with the latest commit. Can you confirm that?

**Comment by rafadesu** [comment]
Yes, sorry I couldn't answer earlier, busy week. It is fine now. Thank you!
