### ISSUE TITLE
Parse bug in {{%include%}} statement

### ISSUE THREAD

**Issue by fishjump** [pantor/inja#164]
# Environment: 
- wsl2 ubuntu 
- g++ 7.5

# Minimum Sample
Json Code:
``` json
{
    "a": {
        "b": {
            "c": 1
        }
    }
}
``` 
``` 
{# template1 #}
## for key, value in a
{%include "template2"%}
## endfor
```
```
{# template2 #}
## for _key, _value in value
    {{log(_value)}}
## endfor
```
``` c++
// log function
env.add_callback("log", 1, [](inja::Arguments &args) {
    nlohmann::json tmp = args.at(0)->get<nlohmann::json>();
    std::cout << tmp << std::endl;
    return "";
});
```
expected output:
```json
1
```
true output;
```
{"parent":1}
```

# My conclusion:

1. It only happens in {{%include}} statement, if I move the second object for loop into first template, it works well.
2. Json data works well outside the second object for, 
e.g. 
```
{# template2 #}
{{{log(value)}}
## for _key, _value in value
    {{log(_value)}}
## endfor
```
the output is
```
{"c":1}
{"parent":1}
```
3. The "key" works well.
4. I also tested array for loop by changing "b" to a json array, then the program throw a runtime exception 
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with a string argument with number
Aborted
```
4. I think this issue may be caused by json_input is assigned to json_loop_data  or current_loop_data somewhere(high probability in void visit(const IncludeStatementNode& node)). I'll keep work on this issue, and I'll feel happy if there's any support.

**Comment by fishjump** [comment]
# Update
Located bug on 
``` c++
auto result = eval_expression_list(node.condition);
if (!result->is_object()) {
    throw_renderer_error("object must be an object", node);
}
if (!current_loop_data->empty()) {
    (*current_loop_data)["parent"] = std::move(*current_loop_data);
}
```
I'm finding the reason why result gets a same address of current_loop_data

**Comment by fishjump** [comment]
Bug is fixed. Just add one statement.
''' c++
current_loop_data = &json_loop_data["loop"];
'''
Put the above code in the if branch of render_to. Because current_loop_data is initialized before call render_to when json_loop_data is an uncertain value(usually nullptr), thus, occasionally, result I mentioned above was overwritten by a wrong current_loop_data. 

I am not allowed push code to public(like github) during my work time. I'll clone this repo and PR 8 hours later.

**Comment by pantor** [comment]
HI @fishjump, awesome work! Thanks a lot!
