### ISSUE TITLE
Limit scope of include statement

### ISSUE THREAD

**Issue by tindy2013** [pantor/inja#167]
My program is providing a web API where everyone can render their own template, but this opens up a vulnerability that they can use the `{% include %}` statement to reach any file on the server. To avoid that and allows anyone to include templates only from one directory, I am currently using [a simple but ugly method](https://github.com/tindy2013/subconverter/blob/master/include/inja.hpp#L3173-L3184) in my project. Is there a better implementation for this except using file permissions to limit the whole program?

**Comment by tindy2013** [comment]
PS: Figured out a way: check if the full path of the included template starts with the include scope.
And for getting the full path of a file/folder, the C++ standard library way is:

**Comment by sdlime** [comment]
+1 on this as a really useful enhancement.

**Comment by pantor** [comment]
Inja now supports an include callback, so that you can implement an own file handler easily. From the Readme:
```.cpp
// The callback takes the current path and the wanted include name and returns a template
env.set_include_callback([&env](const std::string& path, const std::string& name) {
  // Find and return a template here
  return env.parse("Hello!");
});
```
In particular, you can disable to search for templates in the file system via `env.set_search_included_templates_in_files(false)`.
