### ISSUE TITLE
 How to use double loop

### ISSUE THREAD

**Issue by xbotao** [pantor/inja#168]
hi,

I have a problem to use double loop.

If the json object like this:

```
{
	"data_list": [{
			"name": "data1",
			"values": ["Jeff", "Tom", "Patrick"]
		},
		{
			"name": "data2",
			"values": ["Jeff2", "Tom2", "Patrick2"]
		}
	]
}
```

```
json data_list;

json data1;
data1["name"] = "data1";
data1["values"] =  {"Jeff", "Tom", "Patrick"};

json data2;
data2["name"] = "data2";
data2["values"] =  {"Jeff2", "Tom2", "Patrick2"};

data_list.push_back(data1);
data_list.push_back(data2);
```

There is an error when  I use the follow code to print something.

```
{%  for data in data_list %}
{%  for value in data.values%}
{{ value }}
{%  end for %}
{%  endfor %}
```

Thanks!

**Comment by pantor** [comment]
Hi @xbotao,

what exact error message do you get? By the way, it needs to be `endfor` not `end for` in your example.

**Comment by xbotao** [comment]
> Hi @xbotao,
> 
> what exact error message do you get? By the way, it needs to be `endfor` not `end for` in your example.

data.values "data.values" not found

**Comment by xbotao** [comment]
That's Ok.

**Comment by pantor** [comment]
Hi, how did you fix your issue?

**Comment by xbotao** [comment]
> Hi, how did you fix your issue?


Sorry, my code is not correct!

**Comment by Mr-Jonas** [comment]
so did you get for loop to work ? If i may ask.
