### ISSUE TITLE
Can't use ## for inside an included template

### ISSUE THREAD

**Issue by thekiwicoder0** [pantor/inja#170]
I'm receiving an error when including a template containing a ## for construct.

The specific error is:
[json.exception.type_error.305] cannot use operator[] with a string argument with string

More specifically, I am including like this:
`{% include "test_template.txt" %}`

Where test_template.txt contains this:
```
## for i in range(3)
Hi
## endfor
```

Am I missing something here?

**Comment by thekiwicoder0** [comment]
Ok this was only happening with 3.0.0 release. Not happening on main.

**Comment by georgbuechner** [comment]
Okay, I'm using inja 3.0 as this version is currently the only one accessible through conan. Is there a planed fix? Or does anybody no about versions, where this is not the case, which are accessible through conan?
