### ISSUE TITLE
Plans for adding other Jinja2 functionalities?

### ISSUE THREAD

**Issue by tindy2013** [pantor/inja#171]
Are there any plans for adding other Jinja2 functionalities like `macro`, `block`, `extends` statements and filters? Jinja2Cpp has implemented these, but the heavy usage of Boost libraries makes it too far from lightweight, so I am hoping that inja can support them in a simple way. Thank you!

**Comment by pantor** [comment]
I'm not currently working on any of these features, but I have them in my mind.

Of course, I would welcome any PR!

**Comment by pantor** [comment]
PR #198 adds support for the child inheritance features including `block` and `extends`.

**Comment by pantor** [comment]
As #198 is now merged, I'll close this issue. Please open a new issue for the `macro` (or other) feature of Jinja2.
