### ISSUE TITLE
Commented out html code will still be recognized and replaced

### ISSUE THREAD

**Issue by jiangbinzhe** [pantor/inja#173]
as this
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>1</th>
      <th>2</th>
      <th>3</th>
      <th>4</th>
      <th>5</th>
      <th>6</th>
    </tr>
  </thead>
  <tbody>
                    
    <tr>
      <th>{{ value1 }}</th>
      <td>{{ value2 }}</td>
      <td>{{ value3 }}</td>
      <td>{{ value4 }}</td>
      <td>{{ value5 }}</td>
    </tr>
  </tbody>
</table>

**Comment by pantor** [comment]
This is intended behavior. Inja itself doesn’t know about HTML comments and should replace the whole document.

Why does it matter to you? HTML comments will still be comments after rendering. Is it just for performance reasons?
