### ISSUE TITLE
Loop example from docs throws exception

### ISSUE THREAD

**Issue by Mr-Jonas** [pantor/inja#174]
Hi There
Thank you for making inja. It's a very nice lib.

But I  was wondering what possible I can be doing wrong.
I can't get any **for** loop to work. not even the one from the docs!?
(code directly from docs) 

json data;
data["neighbour"] = "Peter";
data["guests"] = {"Jeff", "Tom", "Patrick"};
data["time"]["start"] = 16;
data["time"]["end"] = 22;

render(R"(Guest List:
`##` for guest in guests
	{{ loop.index1 }}: {{ guest }}
`##` endfor )", data);

It throws an exception with  loop.index1 not found/existing
if i then remove that so its only
{{ guest }}
it says guest is not found/existing.

I'm using win 10
visual studio 2017

So where can i find a working example of the for statement ?
Could be something with my compiler ?

**Comment by pantor** [comment]
Hi! Which specific inja and nlohmann/json version do you use? This might be related to older json versions, so make sure that you are up to date.

**Comment by Mr-Jonas** [comment]
Hi. thank you for fast reply. I think its version nlohmann/json v3.6.1 and while looking for the version of inja, i found that
inja might expect nlohmann/json 3.8.0
So I will try to update and see. Everything else worked so didnt not strike me it was/might the json :) thank you.
Will report back.

**Comment by Mr-Jonas** [comment]
Updating the json seemed to help.  At least fast test would loop an array.  I also updated inja but then my app crashed. I assume its my app :)  Thank you for your support.
