### ISSUE TITLE
Eaten {

### ISSUE THREAD

**Issue by viktor-irafm** [pantor/inja#176]
variable = 1
template: {{{ variable }}}

expected result: {1}

obtained result: 1}

issue: the first brace is removed.

workaround: { {{ variable }} } gives { 1 } but with extra space symbol.

**Comment by pantor** [comment]
`{{{ variable }}}` is not a valid template syntax. Regular text (the third `}`) is not allowed within a variable expression, and is ignored currently. Then the first two `}}` will close the variable expression and the final `}` outside of the expression will be added to the result.

`{ {{ variable }} }` will always print one extra space symbol. If you want to print braces flexibly, we recommend to switch the expression syntax e.g. via `env.set_expression("%%", "%%");` and use `{%% variable %%}`.
