### ISSUE TITLE
Distribution via conda-forge

### ISSUE THREAD

**Issue by jessemapel** [pantor/inja#179]
I'm working to integrate inja into a c++ project that is using [Anaconda](https://www.anaconda.com/) to manage its dependencies. I'd like to make inja available via [conda-forge](https://conda-forge.org/) so that I can just add it to my environment via Anaconda and not have to manage a sub-module.

I already maintain a handful of packages on conda-forge and would be happy to do the work involved in getting it staged and maintained there. I want to check in with the maintainers here if they are okay with this before re-packaging their work.

I also have two questions about exactly how and which headers need to be installed. From the docs, it sounds like either the full set of headers can be included or the single header but not both. For a distribution, which option should be included? Some of the headers have very common names, would it be reasonable to install them into `include/inja/`?

**Comment by pantor** [comment]
Hi, that would be awesome! 👍 

I think it would be better to distribute the full set of headers, as the combined *single-include header* is only useful for faster manual installation. Yes, `include/inja/` is the preferred directory for installation. If there are any more questions, feel free to ask. Thanks!

**Comment by jessemapel** [comment]
PR into conda-forge staged recipes it up at https://github.com/conda-forge/staged-recipes/pull/13518

I'll update here with the full feedstock once that's done. There's also a badge you can add to the Readme if you'd like once the feadstock is up.

**Comment by jessemapel** [comment]
The package is now up and available on Anaconda at https://anaconda.org/conda-forge/inja. 3.1.0 with #177 is what's available on the feedstock.

If anyone has issues with the conda-forge build please post over at the [feedstock](https://github.com/conda-forge/inja-feedstock).

I will follow up next week with a PR adding installation instructions to the Readme.
