### ISSUE TITLE
Ambiguous example in README

### ISSUE THREAD

**Issue by 00ff0000red** [pantor/inja#182]
This particular example isn't clear:
```c++
// Standard comparisons with variable
render("{% if time.hour >= 20 %}…{% else if time.hour >= 18 %}…{% endif %}", data); // True
```

It simply says true, but it's an `if` `else if`.
Imho, it should just be an `if else`.

Should it be interpreted like so?
```
{% if time.hour >= 20 %} True {% else if time.hour >= 18 %} False {% endif %}
```

or
```
{% if time.hour >= 20 %} True {% else if time.hour >= 18 %} True {% endif %}
```

Since we're looking at the condition itself.

**Comment by pantor** [comment]
That's indeed not very clear. I've just improved the example in the readme, I hope that clears up any ambiguity.
