### ISSUE TITLE
Warning about unused parameter 'node' in 'get_argument_vector' function

### ISSUE THREAD

**Issue by mtiapko** [pantor/inja#183]
Hi!

I'm getting warnings about `unused parameter 'node'` in this function:
https://github.com/pantor/inja/blob/3cc82e934e25a2ce578f9dec5cd6d3bff035753d/include/inja/renderer.hpp#L121

Function `get_arguments` uses `node` parameter to throw exception. So I don't know if it is right to remove `node` parameter from `get_argument_vector` function, or it is better to add a similar check as in `get_arguments` function:
https://github.com/pantor/inja/blob/3cc82e934e25a2ce578f9dec5cd6d3bff035753d/include/inja/renderer.hpp#L98-L101

Compiling using `g++ 10.2.0` with `-Wall -Wextra` flags.

**Comment by pantor** [comment]
You're right, there should be a check 👍 I've added one with the latest commit to the master branch, so this issue should be fixed.
