### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by matusnovak** [pantor/inja#184]
Hi there!

I would like to submit a PR to [vcpkg](https://github.com/microsoft/vcpkg) to update this library port file to the latest version (currently the port file is at v3.0.0). The change merged from #177 is needed to do so, but it is not a part of a release at the moment. Would it be possible to create a new release v3.2.0?

I know that you can simply use `vcpkg install --head inja` which downloads the latest master, but I would like to keep the consistency and update the portfile on vcpkg.

Thanks!

**Comment by pantor** [comment]
[Here](https://github.com/pantor/inja/releases/tag/v3.2.0) we go... Thanks for updating the port file on vcpkg!

**Comment by matusnovak** [comment]
Thank you!
