### ISSUE TITLE
Support dollar sign or at sign ?

### ISSUE THREAD

**Issue by gauss02** [pantor/inja#185]
json data;
data["name"] = "name";
data["_name"] = "_name";
data["$name"] = "$name";
data["@name"] = "@name";
data["_$name"] = "_$name";
data["_@name"] = "_@name";
std::cout<<data.dump(2) <<std::endl;
std::cout<<render("Hello 1 {{ name }}!", data) <<std::endl;
std::cout<<render("Hello 2 {{ _name }}!", data) <<std::endl;
std::cout<<render("Hello 3 {{ $name }}!", data) <<std::endl;
std::cout<<render("Hello 4 {{ @name }}!", data) <<std::endl;
std::cout<<render("Hello 5 {{ _$name }}!", data) <<std::endl;
std::cout<<render("Hello 6 {{ _@name }}!", data) <<std::endl;

{                                                                     
  "$name": "$name",                                                   
  "@name": "@name",                                                   
  "_$name": "_$name",                                                 
  "_@name": "_@name",                                                 
  "_name": "_name",                                                   
  "name": "name"                                                      
}                                                                     
Hello 1 name!                                                         
Hello 2 _name!                                                        
Hello 3 name!                                                         
Hello 4 name!                                                         
terminate called after throwing an instance of 'inja::RenderError'    
  what():  [inja.exception.render_error] (at 1:12) malformed expression

**Comment by pantor** [comment]
This should be fixed with the latest commit. Thanks for the feedback!
