### ISSUE TITLE
Suspected regression in whitespace control feature

### ISSUE THREAD

**Issue by mydatamodels** [pantor/inja#186]
Hello,

IMO version 3.1.0 is not consistent with what is stated in the documentation, i.e.

> `set_lstrip_blocks` strips tabs and spaces from the beginning of a line to the start of a block

If I execute something like that:
```
#include <iostream>

#include "inja/inja.hpp"

using namespace inja;
using json = nlohmann::json;

int main() {
  json data;
  data["name"] = "world";

  Environment env;
  env.set_trim_blocks(true);
  env.set_lstrip_blocks(true);

  auto out = env.render(
      "    {% if exists(\"name\") %}    Hello {{ name }}!{% endif %}", data);

  std::cout << out << "\n";

  return 0;
}
```
with 2.2.0 the whitespace after the if block isn't stripped:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/52713225/105525744-c3f5e080-5ce1-11eb-890c-9b498f2ffa6b.png">

with version 3.1.0, on the other hand, I get:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/52713225/105525806-d8d27400-5ce1-11eb-8eb9-274029e0fe44.png">

Is this a regression or am I missing something? Is there a way to come back to the previous behavior?

Thanks and best regards.

**Comment by WimLeflere** [comment]
I also have the impression that the feature is no longer working as stated in the readme.

**Comment by pantor** [comment]
This seems to work as intended, as both `set_trim_blocks` and `set_lstrip_blocks` are set to true. In particular, `set_trim_blocks` removes whitespaces up to the first newline after a statement, which therefore removes the whitespaces after the if statement in your example.

```
"    {% if exists(\"name\") %}    Hello {{ name }}!{% endif %}"
```

The whitespaces before the if statement are removed because of `set_lstrip_blocks`.

**Comment by WimLeflere** [comment]
These are the results I get with 3.2.0
Code
```
#include <iostream>
#include <inja/inja.hpp>

int main()
{
   auto data = nlohmann::json();
   data["name"] = "Inja"; 

   std::cout << inja::render("'Hello    {{- name -}}    !'", data) << '\n';
}
```
Output
```
'Hello    Inja!'
```

I was expecting
```
'Hello Inja!'
```

**Comment by mydatamodels** [comment]
> In particular, `set_trim_blocks` removes whitespaces up to the first newline after a statement, which therefore removes the whitespaces after the if statement in your example.

Thanks for you answer. What you're saying makes totally sense, I've been mislead by what is written in the readme about `set_trim_blocks`: 

`While enabling set_trim_blocks removes the first newline after a statement`
