### ISSUE TITLE
Idea: Ability to store parsed templates

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#19]
Maybe it would be great to be able to store parsed template in some binary format for some kind of caching. 

Based on my first measures it seems that a lot of time is spent in parser:

```
total : 2942.00ms

Initialization: 45.70ms
Parser:  2882.51ms
Render:: 13.61ms
```

Do you think it would be possible to serialize template file and back?

**Comment by pantor** [comment]
I think a binary format for parsed templates would be too heavy for a header-only library.

But I'm sure there are a lot of possible optimizations, so that the time for parsing can be reduced drastically. I think that should be the way to go.
