### ISSUE TITLE
Null pointer dereferencing provokes SIGSERV

### ISSUE THREAD

**Issue by rafadesu** [pantor/inja#191]
Hi,

This template seems to be provoking the issue:

{{ at(variable_name, 1).member \n }}

Actually, any text added after finishing the at expression would cause the crash. It is not valid syntax but it shouldn't crash.

I've tested with latest version in master branch and it is reproducible.

The problem seems to be happening in case Op::AtId, dereferencing pointer variable "container" in single_include/inja/inja.hpp:3643

**Comment by rafadesu** [comment]
Adding:
```
+ if (container != nullptr)
     json_eval_stack.push(&container->at(id_node->name));
```
seems to fix it.

**Comment by pantor** [comment]
This should be fixed with the latest commits on master. Can you confirm this?
