### ISSUE TITLE
Include in-memory templates and parse_template()

### ISSUE THREAD

**Issue by Tectu** [pantor/inja#192]
It seems that using in-memory templates together with a template that is parsed as a file using `Environment::parse_template()` doesn't work. Is this correct?

When I do this:
```cpp
using namespace inja;

Environment env;

const auto parsed_body_template = env.parse("Hello World {{ system.link }}");
env.include_template("body", parsed_body_template);

nlohmann::json data;
// Fill JSON data

Template tmpl = env.parse_template("index.html");
const std::string str = env.render(tmpl, data);
```
With `index.html` containing:
```
<html>
    <body>
        <div>
            {% include "navigation.html" %}
        </div>

        <div class="main-content">
            {% include "body" %}
        </div>
    </body>
</html>
```

I receive the exception:
```
exception during template rendering: [inja.exception.file_error] failed accessing file at '../plugins\admin\assets\admin/body'
```
However, inclusion of the template file `navigation.html` works flawlessly.

Is this is a bug, a limitation or am I missing something else?
Basically I want to use the `Environment::parse_template()` method to parse a template file which includes other template files but also uses an in-memory template as per the code snipped shown above.

I'm using `v3.2.0`.

**Comment by alex-kuzza-aaa** [comment]
Could  you try, this?

Instead of :
Template tmpl = env.parse_template("index.html");
const std::string str = env.render(tmpl, data);

do that:
const std::string str = env.render_file("index.html", data);

**Comment by Tectu** [comment]
After applying your suggested change, I am still experiencing the same issue.

**Comment by pantor** [comment]
This should be fixed now on master. Can you confirm?

**Comment by Tectu** [comment]
Yep - seems to work now as expected.
Thank you for this great library - keep it up!
