### ISSUE TITLE
Join values between {}

### ISSUE THREAD

**Issue by WimLeflere** [pantor/inja#199]
What is the recommended way to join some values between curly braces?
I'm trying to render `{1, 2, 3, 4}` based on a vector of ints.

Rendering the vector directly results in `[1,2,3,4]`.

My first try of using a loop resulted in `{ 1,  2,  3,  4, }`.
I added a condition to not add the last separator (`, `), a bit cumbersome, with the result `{ 1,  2,  3,  4}`.

How can I remove the space after the first brace? `{{% for ...` results in a parse error.
Using whitespace control (`{ {%- for`) didn't remove the space.
Is there a way to escape a brace?

```
  auto data = nlohmann::json();
  data["values"] = std::vector{1, 2, 3, 4};

  auto env = inja::Environment();
  std::cout << env.render("{{ values }}\n", data);
  std::cout << env.render("{ {% for value in values %}{{ value }}{% if not loop/is_last %}, {% endif %}{% endfor %}}\n", data);
```

**Comment by pantor** [comment]
Hi @WimLeflere,

as your template makes use of braces, I'd strongly recommend to change the opening and closing strings to non-brace characters. For example, you could do
```
env.set_expression("[[", "]]");
env.set_statement("[%", "%]");

env.render("{[% for value in values %][[ value ]][% if not loop/is_last %], [% endif %][% endfor %]}", data); // returns {1, 2, 3, 4}
```

Another possibility would be to write a C++ rendering method as a [callback](https://github.com/pantor/inja#callbacks). At the moment, inja does not support escaping a brace. Also note that you could do

```
env.render("{ {% for value in values %}{{ value }}{% if not loop/is_last %},{% endif %} {% endfor %}}", data); // returns { 1, 2, 3, 4 }
```
to have at least symmetric whitespace around the braces.

**Comment by WimLeflere** [comment]
Thanks for the info.

Would you be interested in a PR which adds a `join` function?
E.g. `render("{{ join(guests, \" - \") }}", data); // "Jeff - Patrick - Tom"`

**Comment by pantor** [comment]
The `join` function sounds useful - I would be happy to merge a PR.
