### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by GaRaOne** [pantor/inja#205]
### comparison

> In file included from ../../sdk/inja/include/inja/inja.hpp:18:
> In file included from ../../sdk/inja/include/inja/environment.hpp:16:
> ../../sdk/inja/include/inja/parser.hpp:55:53: warning: unused parameter 'message' [-Wunused-parameter]
>   inline void throw_parser_error(const std::string &message) {
>                                                     ^
> ../../sdk/inja/include/inja/parser.hpp:84:26: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
>     for (size_t i = 0; i < function->number_args; ++i) {
>                        ~ ^ ~~~~~~~~~~~~~~~~~~~~~

### init order

> In file included from ../../sdk/inja/include/inja/inja.hpp:18:
> In file included from ../../sdk/inja/include/inja/environment.hpp:16:
> In file included from ../../sdk/inja/include/inja/parser.hpp:17:
> ../../sdk/inja/include/inja/node.hpp:355:115: warning: field 'parent' will be initialized after field 'name' [-Wreorder-ctor]
>   explicit BlockStatementNode(BlockNode *const parent, const std::string& name, size_t pos) : StatementNode(pos), parent(parent), name(name) { }

### unused variables

(void)loc;
(void)message;

> In file included from ../../sdk/inja/include/inja/inja.hpp:18:
> In file included from ../../sdk/inja/include/inja/environment.hpp:17:
> ../../sdk/inja/include/inja/renderer.hpp:101:20: warning: unused variable 'loc' [-Wunused-variable]
>     SourceLocation loc = get_source_location(current_template->content, node.pos);
>                    ^
> ../../sdk/inja/include/inja/renderer.hpp:100:48: warning: unused parameter 'message' [-Wunused-parameter]
>   void throw_renderer_error(const std::string &message, const AstNode& node) {

> In file included from ../../sdk/inja/include/inja/inja.hpp:18:
> In file included from ../../sdk/inja/include/inja/environment.hpp:16:
> ../../sdk/inja/include/inja/parser.hpp:55:53: warning: unused parameter 'message' [-Wunused-parameter]
>   inline void throw_parser_error(const std::string &message) {

**Comment by pantor** [comment]
Should all be fixed with the latest commit!
