### ISSUE TITLE
Use set statement to precalculate values

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#211]
Hi,

is there any way how to concat several variables in set command?

Something like 

`{% set var=v1+v2 %}`

Thanks

**Comment by injamies** [comment]
This works for me as expected.

```cpp
{% set v1 = "a" %}
{% set v2 = "b" %}
{% set var = v1 + v2 %}
{{ var }}
```

This also works with numbers.

**Comment by ludekvodicka** [comment]
Thanks for the reply. I have to try it again, but I received some errors.

**Comment by pantor** [comment]
I've added @injamies examples to the CI tests and it works well, so I'll close this for now. If your issue persists, feel free to reopen with a few more details @ludekvodicka.
