### ISSUE TITLE
Ignore the "variable `x` not found" exception

### ISSUE THREAD

**Issue by CncGpp** [pantor/inja#215]
Hi! There is a way to ignore (and skip) the variable not foud exception during the rendering of a string?

For example the code:
`inja::render("SELECT {{columns}} FROM {{table_name}} LIMIT {{limit}}", { { "table_name","TPCH" } });`
I'd like to get:
`"SELECT {{columns}} FROM TPCH LIMIT {{limit}}"`

**Comment by pantor** [comment]
You could use the `default` function:
```
inja::render("SELECT {{ default(columns, \"{{columns}}\") }} FROM {{table_name}} LIMIT {{ default(limits, \"{{limits}}\") }}", { { "table_name","TPCH" } });
```

**Comment by CncGpp** [comment]
Yes I knew it, but unfortunately it is not what I was looking for.
I solved it by creating a kind of 'defaultdict' by extracting all or values of the string with a regular expression.

**Comment by mbessler** [comment]
It would be nice if there was an option to render a variable to an empty string if variable is not defined, similar to (what I remember from) Jinja2.
