### ISSUE TITLE
Mathematical operation

### ISSUE THREAD

**Issue by MattiasEppler** [pantor/inja#219]
Hi see this in the examples.
`render("{% if guest_count < (3+2) and all_tired %}Sleepy...{% else %} ... ", data );`

you can do an addition.

But following will throw an exception
`render("{% set guest_count = (3+2) %} " , data );
`
Why?

**Comment by pantor** [comment]
Hi @MattiasEppler, there was an error while lexing numbers without whitespaces in between. The latest commits fix that, and your example above should work fine.
