### ISSUE TITLE
Functions to convert string to number

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#22]
Because Inja now offers several useful function it would be great to add also functions to convert string to number.

I currently have these functions named `double(x)` and `integer(x)` with following test

	nlohmann::json data;
	data["val1"] = "5";
	data["val2"] = "-5";

	InjaStringType res = inja::render("{%if integer(val1) >= 0%}yes{%else%}no{%endif%}", data);
	TEST_CHECK_EQUAL(res, "yes");

	res = inja::render("{%if integer(val1) < 0%}yes{%else%}no{%endif%}", data);
	TEST_CHECK_EQUAL(res, "no");

	res = inja::render("{%if double(val2) >= 0%}yes{%else%}no{%endif%}", data);
	TEST_CHECK_EQUAL(res, "no");

	res = inja::render("{%if double(val2) < 0%}yes{%else%}no{%endif%}", data);
	TEST_CHECK_EQUAL(res, "yes");

Are you interested in such PR?

**Comment by pantor** [comment]
Already done!

**Comment by ludekvodicka** [comment]
Thanks!
