### ISSUE TITLE
Feature Request: Support custom macros of nlohmann_json

### ISSUE THREAD

**Issue by chirsz-ever** [pantor/inja#222]
I use nlohmann_json with `JSON_USE_IMPLICIT_CONVERSIONS=0` and `JSON_NO_IO=1`, but inja uses the io feature:

https://github.com/pantor/inja/blob/eb04bfc7d3cf0a5fbd0ed37a88d064230d0af377/include/inja/renderer.hpp#L451-L472

https://github.com/pantor/inja/blob/eb04bfc7d3cf0a5fbd0ed37a88d064230d0af377/include/inja/environment.hpp#L162-L171

Could you please support with `JSON_NO_IO=1`?

**Comment by chirsz-ever** [comment]
The macros document: https://github.com/nlohmann/json/blob/master/doc/mkdocs/docs/features/macros.md

**Comment by pantor** [comment]
Hi! The latest commits add support for `JSON_NO_IO` and `JSON_USE_IMPLICIT_CONVERSIONS` (although the latter seemed to work fine before). Also thank you for the PR, even I did not merge it!
