### ISSUE TITLE
Problem Accessing Keywords Starting with "^"

### ISSUE THREAD

**Issue by acpaquette** [pantor/inja#224]
I have a PVL string that is being converted into JSON then being given to inja to render a template.

The problem I am seeing is that one of the JSON keywords I am trying to access is "^QUBE" at the root of the JSON tree. If I had to take the a guess the tokenizer is trying to apply something to the power of whatever QUBE is. But since there is no number to take to the power of QUBE the whole expression just fails to render.

Is there some good work around for this? Some way to ignore all mathematical render operations and treat everything as a key in the json?

Here is the json blob:
```
{
    "^QUBE": {
        "Value": "203"
    }
}
```

And here is how I am trying to access it:
```
OriginalLabelOffset = {{ ^QUBE.Value }}
```

If there is no work around or it will take some time to get to I think my team and I will be able to come up with a short term work around. I appreciate the assistance and look forward to hearing from you!

**Comment by pantor** [comment]
Hi @acpaquette,

there is indeed a clash with the tokenizer here. Similar to other programming languages, inja variable names cannot start with mathematical symbols like `^`. I would suggest to rename the variable names before passing them to inja. If you really would like to make that work with inja, you could change [this line](https://github.com/pantor/inja/blob/88bd6112575a80d004e551c98cf956f88ff4d445/include/inja/lexer.hpp#L107) from 
```.cpp
return make_token(Token::Kind::Power);
```
to 
```.cpp
return scan_id();
```

**Comment by acpaquette** [comment]
Cool, that's along the lines of changing inja to suit our needs but I think your suggestion of renaming the key before passing the json off to inja is the better solution. Thank you for the prompt response!
