### ISSUE TITLE
Feature Request: Function for string type: `startsWith` and `endsWith`

### ISSUE THREAD

**Issue by kiddliu** [pantor/inja#225]
The problem I'm Trying To Solve
I'm working on a language-projection project, and there's a lot of literal forms of a data type, along with a huge amount of auxiliary type info.

Current Solution
Without these basic string helper functions, I have to create a bunch of different JSON attributes to represent these auxiliary type infos.

Requested Solution
It would be very nice if I could have the following:

```
#include <string>

#include "data.h"
#include "util.h"

## for namespace in namespaces
    {% if startsWith(namespace, "std") %} ... {% else %} ... {% endif %}
## endfor
```

**Comment by hstejas** [comment]
I have used this for the same purpose

```
    inja::Environment env;
    env.add_callback("starts_with", 2, [](const inja::Arguments& args) {
        return args.at(0)->get<std::string_view>().starts_with(args.at(1)->get<std::string_view>());
    });
```

```
{% if starts_with("xyz", "x") %}
```

**Comment by kiddliu** [comment]
How can I bypass this whole `Callback` section in the doc! Thank you, @hstejas.
