### ISSUE TITLE
nested function within array not recognized

### ISSUE THREAD

**Issue by mbessler** [pantor/inja#227]
With 3.3.0, I tried nested functions, where the inner function is enclosed in an array:
```
json data;
std::string test = R"({{ max([1,2,3,4,5,default(some.property, 9)]) }}  )";
std::cout << env.render(test, data) << std::endl;
```
which yields this error:
```
terminate called after throwing an instance of 'inja::ParserError'
  what():  [inja.exception.parser_error] (at 1:84) unknown function default
```

Function nesting works fine without the array.

Should this be supported?

**Comment by pantor** [comment]
This is currently not supported and has the same underlying issue as #151. Basically, inja would need to reimplement a complete JSON parser (or at least use the internal interface of nlohmann/json) for that.
