### ISSUE TITLE
How to check for key existence in an array item?

### ISSUE THREAD

**Issue by kagi3624** [pantor/inja#228]
I have the following array

```
 {       
        "Nissan": [
            {"model":"Sentra", "doors":4, "color": "green"},
            {"doors":40},
            {"model":"Maxima", "doors":4, "color": "black"},
            {"model":"Skyline", "doors":2, "color": "blue"}
        ]
 }
```
Is it possible to check every array item for a key in a for loop? Something like this

```
## for x in Nissan
{% if exists("x.model") %}
{{ x.model}}    -  {{loop.index1}}
{%endif%}
## endfor
```
This seems to me natural to is x.model like that, but it does not work. Also `exists("Nissan.1.model")` seems to check the whole array, and returns false if it is missing in one item. If there is no check, an exception is thrown, because x.model does not exists in the second item.

I have an ugly solution like that. Still don't understand why I can't check for existence simply with `x.model` 
```
## for x in Nissan
{~ set model_ex = false ~}
{~ for key, value in x ~}  
{~if key == "model" ~}
{~ set model_ex = true ~}
{~ endif ~} 
 {~ if (model_ex) ~} {{ x.model}}    -  {{loop.parent.index1}}\\ {~endif~}
{~endfor~}
## endfor
```

**Comment by bbdb68** [comment]
existsIn(x,"model") does not work ?

**Comment by kagi3624** [comment]
THX, this works. It would be nice to add this in the tutorial.
