### ISSUE TITLE
Make Environment::input_path and Environment::output_path protected instead of private

### ISSUE THREAD

**Issue by OndrejPopp** [pantor/inja#235]
Hi, I wanted to implement an output_path stack in a derived class from the Environment class, but now I can't because Environment:: output_path is private.

I need this for generation of many files in a directory tree, where I could "push" and "pop" the current output_path while going through the directories. Of course I could push/pop entire environments but this looks like overkill when you only need an other output_path. In addition it is a bit inconvenient when a new Environment instance needs to be configured with the same configuration options, and creating Environment instances is more resource intensive than creating only new output_path entries.

Thanks!

**Comment by pantor** [comment]
This should be fixed with the latest commit on the master branch. Thanks for your feedback!

**Comment by OndrejPopp** [comment]
Great, tx Berscheid.
Have a nice day.
Ondrej 

⁣Get BlueMail for Android ​
