### ISSUE TITLE
Int type overflow

### ISSUE THREAD

**Issue by xiaozhuai** [pantor/inja#236]
```
int main() {
    inja::Environment env;

    env.add_callback("now", 0, [](const inja::Arguments &args) {
        return (int64_t) (std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count());
    });

    std::cout << env.render(R"(now: {{ now }} {{ now + 10 }})", {}) << std::endl;

    return 0;
}
```

It shows `now: 1646820101281 1847626923`
`now` return `int64_t`, and `now + 10` seems `int32_t`

**Comment by abu-noor** [comment]
Inja limits range to `<int>`, where as the json.hpp file uses `<long long>`. You may be able to modify the single include file at line: 2329. From  `make_result(args[0]->get<int>() + args[1]->get<int>());` to `make_result(args[0]->get<long long>() + args[1]->get<long long>());` Of course you would have to do the same for the other math operators. If you use them.

I don't use Inja. I was just checking if I wanted to use it.

**Comment by xiaozhuai** [comment]
@abu-noor Thanks for your solution. I've changed the `int` to `int64_t` for all math operators. It works good.

**Comment by pantor** [comment]
This should be fixed by the latest commit on the master branch. Inja now uses the correct json data type by default.
