### ISSUE TITLE
Search directory ignored when main template passed as string

### ISSUE THREAD

**Issue by davidchall** [pantor/inja#242]
The inja README features the following example:

```c++
render("{% include \"footer.html\" %}", data);
```

But I find the environment's `input_path` isn't searched when the template is passed as a string (instead of passing a file path), so inja complains it is unable to find footer.html.

**Comment by pantor** [comment]
Thanks so much for spotting this!
It should now be fixed on master. Any comments?

**Comment by davidchall** [comment]
Thanks for the quick fix, @pantor! I've tested this locally and things do seem to work as expected. 🎉 

I guess my one question is whether you have an ETA for the next release, so I can include this fix in my package?

**Comment by pantor** [comment]
Great! I’ll release a new version in the next couple of days.
