### ISSUE TITLE
Optimization: Pass json data to renderer as reference

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#25]
Hi,

just figured out that data are passed to renderer as new copy. This cause a lot of overhead. 

It's sufficint to update it to 

`std::string render(Template temp, const json& data)`

the same for

```
Environment::render_template(const Template& temp, const json& data) 
Environment::render(const std::string& input, const json& data)
Environment::render_file(const std::string& filename, const json& data)
inline std::string render(const std::string& input, const json& data) {
```

Do you want me to prepare PR ?

**Comment by pantor** [comment]
Thanks, I've already updated it myself.
