### ISSUE TITLE
Documentation does not reflect the released version

### ISSUE THREAD

**Issue by GooRoo** [pantor/inja#256]
I install `inja` with conan. The latest version there is 3.3.0. 

So, I opened the docs at https://pantor.github.io/inja/ where the header clearly says it's the documentation for 3.3.0. I read about `include_callback` in the documentation, used it in my code, but then couldn't build it since the code is not there.

The problem is that the documentation is built from `master` and not from the latest release tag.

**Comment by pantor** [comment]
We now build the documentation from the latest published release, and not directly from the master branch anymore. Thanks for your input!
