### ISSUE TITLE
Callbacks with zero parameters stopped working

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#26]
Hi, I'm not sure which update did it but now following test throwing exception
```

	inja::Environment env = inja::Environment();
	env.add_callback("xxx", 0, [&env](inja::Parsed::Arguments args, const json &data) {return 42;});

	nlohmann::json data;
	InjaStringType res = env.render("{{ xxx() }}", data);
	TEST_CHECK_EQUAL(res, "42");
```

Callbacks with 1 and more params works ok.

Problem is probably in parsing empty braces "()" because `Parsed::ElementExpression& element` passed to  `json eval_function(const Parsed::ElementExpression& element, const json& data) {`  has invalid `elem.function value` .

**Comment by ludekvodicka** [comment]
Just found it . The reason is that for 0 arguments brackets aren't included in regex.

	```
static Regex function_regex(std::string name, int number_arguments) {
		std::string pattern = name;

		if (number_arguments > 0) {
   		       pattern.append("\\(");
			for (int i = 0; i < number_arguments; i++) {
				if (i != 0) pattern.append(",");
				pattern.append("(.*)");
			}
		        pattern.append("\\)");
		}

		return Regex{"\\s*" + pattern + "\\s*"};
	}
```


I'm suggesting to update it to this one:

```
	static Regex function_regex(std::string name, int number_arguments) {
		std::string pattern = name;
		pattern.append("\\(");

		if (number_arguments > 0) {
			for (int i = 0; i < number_arguments; i++) {
				if (i != 0) pattern.append(",");
				pattern.append("(.*)");
			}
		}
		pattern.append("\\)");
		return Regex{"\\s*" + pattern + "\\s*"};
	}
```

I believe that all callbacks should behave uqually no matter if it's 0 arguments or two. 

I'm using it for my own function `dump()` to dump all context to result template to simplify debugging.

**Comment by pantor** [comment]
I've added the possibility to use callbacks with zero parameters either with or without parenthesis.

**Comment by ludekvodicka** [comment]
perfect, thanks
