### ISSUE TITLE
MSVC in vs2022 warning

### ISSUE THREAD

**Issue by pm100** [pantor/inja#265]
Using inja produces this warning

C:\work\injatools\inja.hpp(2451,71): warning C4244: 'initializing': conversion from 'ValueType' to 'int', possible loss of data

thats on this line

```
    case Op::Round: {
      const auto args = get_arguments<2>(node);
      const int precision = args[1]->get<const json::number_integer_t>(); ,<<<<======
```

easily fixed with an explicit cast

```
    case Op::Round: {
      const auto args = get_arguments<2>(node);
      const int precision = static_cast<int>(args[1]->get<const json::number_integer_t>());
```

**Comment by pantor** [comment]
I think this is fixed by [this commit](https://github.com/pantor/inja/commit/c2ad85db6da5ecd57b0a89ece64af9c6d2b6bf1d). Thanks for reporting!
