### ISSUE TITLE
Build inja_test failed.

### ISSUE THREAD

**Issue by wendajiang** [pantor/inja#276]
```bash
cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
cmake --build build -j2
```
output the
```bash
[ 33%] Building CXX object CMakeFiles/inja_test.dir/test/test.cpp.o
[ 33%] Building CXX object CMakeFiles/single_inja_test.dir/test/test.cpp.o
/Users/david/cpp/inja/test/test.cpp:5:10: fatal error: 'doctest/doctest.h' file not found
#include "doctest/doctest.h"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [CMakeFiles/inja_test.dir/build.make:76: CMakeFiles/inja_test.dir/test/test.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/inja_test.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 50%] Linking CXX executable single_inja_test
[ 50%] Built target single_inja_test
gmake: *** [Makefile:146: all] Error 2
```

on Macos, and cmake version is 3.27.2

**Comment by pantor** [comment]
This works for me and is tested on all platforms in CI. Are you sure that the file `third_party/include/doctest/doctest.h` exists?

**Comment by wendajiang** [comment]
> This works for me and is tested on all platforms in CI. Are you sure that the file `third_party/include/doctest/doctest.h` exists?

I look up the <root>/CMakeLists.txt and the target inja_test not add the include directory. For comparison, the single_inja_test target have the `target_include_directories(single_inja INTERFACE single_include include third_party/include)`

**Comment by yolicap** [comment]
I have a similar issue compiling my code. Were you able to fix this?
