### ISSUE TITLE
Parser crash when invalid {% if %} is used

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#28]
During my development I find following bug. When I wrongly defined second condition as `if` instead of `else if`, parser completely crashed. Here is snippet:

```
{% if context.filterBy == "groupId" %}xxxx
{% if context.filterBy == "ip" %}xxx
{% else %} xxxx
{% endif %}
```

Error

```
Expression: invalid null pointer

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
```

**Comment by ludekvodicka** [comment]
Also wrong space in "end if" is causing the crash.

`{% end if %}` instead of `{% endif %}`

**Comment by pantor** [comment]
Is this fixed with the latest commits?

**Comment by ludekvodicka** [comment]
works correctly now. 

`[inja.exception.parser_error] misordered if statement`

Thanks
