### ISSUE TITLE
How to serve inja template files

### ISSUE THREAD

**Issue by nikoladsp** [pantor/inja#281]
Hi,
a question: what would be the best way to server inja template files - using FastCGI maybe? I am also interest in how to integrate JWT and DB connections - I am considering using inja for a web shop app and researching possibilities. Currently I am between inja and WebToolkit.

Kindest regards

**Comment by pantor** [comment]
Hi. Good question - this is probably a bit outside of my knowledge. I've worked with some C++ servers in the past, e.g. using [uWebSockets](https://github.com/uNetworking/uWebSockets) or [boost beast](https://github.com/boostorg/beast), but inja is very agnostic to the server framework. So, as inja is just a string template library, it will work with all other library stacks.
