### ISSUE TITLE
Loops over not-existing elements

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#29]
In case I have json with variable structure, currently there is no way how to check if node exists before accessing it.

For example:

```
{
   {"includes" : [.... ] } 
   {"data":  [....] }
}
```

where element "includes" is optional. In such situations there is no way how to correctly generate template.

`{% for i in includes %} .... {% endfor %}`

because in `eval_function()` in `Parsed::Function::ReadJson` the exception will be thrown. There are two options how to solve it:

1) change `inja_throw("render_error", "variable '" + element.command + "' not found");` to `return json();` and together with my previous proposal https://github.com/pantor/inja/issues/27 inja correctly skip such statement.

2) introduce new function for test elements.

` {% if exists(includes) %}{%for i in includes%}....{%endfor%}{%endif%}. `

or better:

` {%for i in default(includes,null)%}....{%endfor%}`

but second one also needs change proposed here https://github.com/pantor/inja/issues/27 to be able to proceed `null` correctly

**Comment by pantor** [comment]
With the latest commit, you can use
```
{%for i in default(includes, {})%}....{%endfor%}
```
Is that sufficient for your use case?

**Comment by ludekvodicka** [comment]
ok, I will try it.

**Comment by ludekvodicka** [comment]
I can confirm it works on last version. as same as `default(includes,null)` works correctly.

Thank you
