### ISSUE TITLE
json types that are null are rendered as empty string

### ISSUE THREAD

**Issue by corppeon** [pantor/inja#291]
null types should be rendered as null, not empty string, otherwise invalid json is generated
e.g. output should be
"foo: null" rather than "foo: "

This can be fixed by removing the is_null() block in Renderer::print_data() and falling back to use value->dump()

**Comment by pantor** [comment]
I'd personally keep it the way it is (null objects rendered as empty strings), as I think that json generated is not the most common use-case. Inja is already flexible enough to add a simple custom function to support this.

**Comment by corppeon** [comment]
Thanks, but that leads to invalid json.
foo:
causes errors when read by a json parser, and there is no value present?
foo: null
is the correct way to represent a null value.
