### ISSUE TITLE
Add a hunter package

### ISSUE THREAD

**Issue by jowr** [pantor/inja#3]
Hi, would you be interested in having your library added to the hunter package management? I could file a PR to make this repository comply with the format required by https://github.com/ruslo/hunter . You can see my current changes here https://github.com/pantor/inja/compare/master...jowr:hunter

**Comment by pantor** [comment]
Sure! Honestly I've never heard of hunter, but it looks great.

**Comment by jowr** [comment]
I think we are good to go.

Inja Travis: https://travis-ci.org/jowr/inja/builds/302896532
Inja AppVeyor: https://ci.appveyor.com/project/jowr/inja/build/3

Hunter Travis: https://travis-ci.org/jowr/hunter/builds/302894338
Hunter AppVeyor: https://ci.appveyor.com/project/jowr/hunter-ooopt/build/1.0.3

Should merge the changes directly to the master branch or do you prefer to keep them in a separate branch for now? 

See and ad hoc comparison here: https://github.com/pantor/inja/compare/master...jowr:hunter

**Comment by pantor** [comment]
You can merge it directly to master. :+1:

**Comment by pantor** [comment]
Done. Thank you!

**Comment by jowr** [comment]
Hi, we are not done yet - I currently work on the integration with hunter. To proceed, I need a release of this repository. Could you please create a new release? Either v0.1.1 or v0.1-hunter or something else that suits you better?

**Comment by pantor** [comment]
Anything else I can help with?

**Comment by jowr** [comment]
Yes, use the GitHub website to create a new release based on the current master branch using either v0.1.1 or v0.1-hunter or some other version number.

**Comment by pantor** [comment]
Oh, it should already be [here](https://github.com/pantor/inja/releases/tag/v0.1.1).

**Comment by jowr** [comment]
Oh sorry, my bad. Did not refresh the website.

**Comment by jowr** [comment]
Started the integration: https://github.com/ingenue/hunter/pull/167

**Comment by pantor** [comment]
And [there](https://docs.hunter.sh/en/latest/packages/pkg/inja.html) it is!
