### ISSUE TITLE
Proposal - change is_last / is_first variables to functions

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#31]
Currently it's not possible to test last/first elements if we have two (or more)  nested loops . Would be better to have it as function which enable us to ask for specific item:

```
{% for i in array1 %}
{% for i2 in i.array2 %}

.....
   {% if is_last(i2) %} ... {%endif %}
   {% if is_last(i2) %} ... {%endif %}
...

{% endfor %}
{% endfor %}
```

**Comment by pantor** [comment]
With the latest commit, it is possible to use {{ parent/is_last }} for nested loops.

**Comment by ludekvodicka** [comment]
great. I believe two levels are sufficient. thanks

**Comment by pantor** [comment]
It works for all depths using `parent/parent/parent/is_last` as well.

**Comment by ludekvodicka** [comment]
Oh, I didn't realize that. perfect.
