### ISSUE TITLE
How to test for not last item? 

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#32]
I'm trying to find a way how to test "it's not last item" but without success

```
{% for i in items %}
   {% if not(is_last) %} .... doesn't work, throws "[inja.exception.render_error] unknown function in renderer: "
   {% if is_last ==0 %} doesn't work too, throws "[inja.exception.render_error] variable '/is_last==0' not found"
{% endfor %}
```

For now I introduced new variable not_last to solve it. 

`data_loop["not_last"] = (i != list.size() - 1);`

But I'm curious what is the correct way. Thanks

**Comment by pantor** [comment]
The right way would be:
```
{% for i in items %}
   {% if not is_last %} ...
{% endfor %}
```
Note the missing parenthesis.

**Comment by pantor** [comment]
I've added a test case with
```
{% for i in items %}
   {% if is_last == false %} ...
{% endfor %}
```
and it seems to be working.

**Comment by ludekvodicka** [comment]
Thanks. I already found it and add it to main page examples ;-)

Regarding == false, it seems like bug in regex parser, because

`{% if is_last == false %}` works but

`{% if is_last==false %}` throws [inja.exception.render_error] variable '/is_last==false' not found

**Comment by ludekvodicka** [comment]
Will be packed form "is_last==false" support or it will be required to use only "is_last == false" form ?

**Comment by pantor** [comment]
In the near future, only `is_last == false` with whitespaces will work.

**Comment by ludekvodicka** [comment]
ok.
