### ISSUE TITLE
Strange space handling in ## commands

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#35]
I believe there is a bug in empty space handling inside and after ## commands

for example:

```
##for i in items
<space><space>value
##endfor
```
generates value directly from the start of the line, not intended via spaces:

`value`

Also, in case there are newlines or empty characters after ## command, newlines and spaces are ignored too:

```
##for i in items
value
##endfor
\n
\r\n
<space><space>\n
##for i in items
value2
#endfor
```

generates :

```
value
value2
```

**Comment by ludekvodicka** [comment]
Also it seems that EOL characters are damaged if ## is used

I have input file in format

```
header <CR><LF>
##for ....
test<CR><LF>
#endfor
footer <CR><LF>
```

but output is

```
header <CR><LF>
test<CR>
footer <CR><LF>
```

This causing huge problems for visual studio compiler (I'm migrating inja also for our in-house code generator).

**Comment by pantor** [comment]
With the latest release of inja v2, quite a lot changed about handling line statements. If you’re still unhappy about the space handling, feel free to open a new issue. Thanks!

**Comment by ludekvodicka** [comment]
Thanks. It's great to see all the progress you made with Inja. As soon as I have some free time I will test it and let you know. 
Thanks!
