### ISSUE TITLE
Segmentation fault: 11 on OS X

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#36]
Hi,

my tests just reveal strange error on OSX (I have several multi platform app on Win/Lin/OSX).

I have these two tests to ensure Inja is working fine in my apps:

```
AX_TEST_CASE(inja_callback7)
{
	inja::Environment env = inja::Environment();
	env.add_callback("fce", 0, [&env](inja::Parsed::Arguments /*args*/, const axJson &/*data*/) {return 42; });

	nlohmann::json data;
	InjaStringType res = env.render("{{ fce }}", data);
	TEST_CHECK_EQUAL(res, "42");
}


AX_TEST_CASE(inja_callback8)
{
	inja::Environment env = inja::Environment();
	env.add_callback("fce", 0, [&env](inja::Parsed::Arguments /*args*/, const axJson &/*data*/) {return 42;});

	nlohmann::json data;
	InjaStringType res = env.render("{{ fce() }}", data);
	TEST_CHECK_EQUAL(res, "42");
}
```
 

First test (callback7) works on any platform without any issues. Second test (callback8) works on Win32/64 as same as Linux 32/64 but on OSX this test ends with Segmentation fault: 11 without any additional info.

The only difference is in () for zero argument callback.

Do you have any idea what can be wrong? I will try to debug it but my primary development environment is Windows so I'm not sure if I will be able to detect the issue by myself.

**Comment by ludekvodicka** [comment]
First observations:

There is missing initialization for enum `function` in struct `ElementExpression` and thanks for this value `function` is `not` == 0.  (Still not sure why function isn't correctly filled like on other platforms). 

But because elementExpression is `not`, during evaluation there is attempt to access his first  elemnt but there is no such element. So this lead to complete crash. It would be better to make checks in each parsed function if there is required number of arguments.

			case Parsed::Function::Not: {
				return not eval_expression<bool>(element.args[0], data);
			}


Also it would be better to intialize it with new "Unknown" element so there will be no such side-effects.

```
struct ElementExpression: public Element {
		Function function{ Function::Unknown };
		std::vector<ElementExpression> args;
```

I will continue during my investigation but it would be great to add these checks to the code.

**Comment by ludekvodicka** [comment]
Next clues:

When parsing tempalte {{ fce() }} there is no match in this function (altough in Linux/Win it's matched):

```
	Parsed::ElementExpression parse_expression(const std::string& input) {
		MatchType<Parsed::CallbackSignature> match_callback = match(input, regex_map_callbacks);
		if (!match_callback.type().first.empty()) {
			std::vector<Parsed::ElementExpression> args = {};
```

And because `match_callback.type().first` is empty it is executed following line

`Parsed::ElementExpression result = Parsed::ElementExpression(match_function.type());`

and because match_function type is uninitialized, match_function.type() returns 0 which means "not" in current implementation, parser evaluate it as not() without any argument.

Still, I'm not sure why this string isn't correctly recognized by Regex

**Comment by ludekvodicka** [comment]
Another problem is, that when there is no match in function `match(), it's returned unititialized `match` variable:


```
template<typename T, typename S>
inline MatchType<T> match(const std::string& input, const std::map<T, Regex, S> &regexes) {
	MatchType<T> match;
	for (const auto &e : regexes) {
		if (std::regex_match(input.cbegin(), input.cend(), match, e.second)) {
			match.set_type(e.first);
			match.set_regex(e.second);
			return match;
		}
	}
	return match;
}
```

because MatchType doesn't have any default initialization:


```
template<typename T>
class MatchType: public Match {
	T type_;

```

It would be better to create "Unknown" value for any type and initialize it so there will be no such side-effects in the future.

**Comment by ludekvodicka** [comment]
And the root of the initial problem is, that this regex `(?:fce|fce\(\))` isn't working on OS X. Altough regexes are the same on all platforms, in OSX this regex is false when is evaluated by 

`if (std::regex_match(input.cbegin(), input.cend(), match, e.second)) {`

and because of that function `match(const std::string& input, const std::map<T, Regex, S> &regexes)` returns unitialized values, which caused all issues mentioned above.

**Comment by ludekvodicka** [comment]
And fix is dammed simple ;-).

It's sufficient to switch regex to test fce() first, so this is the correct form `(?:fce|fce\(\))`

Here is updated `function_regex` : 
```
	static Regex function_regex(std::string name, int number_arguments) {
		std::string pattern = name;
		pattern.append("\\(");
		for (int i = 0; i < number_arguments; i++) {
			if (i != 0) pattern.append(",");
			pattern.append("(.*)");
		}
		pattern.append("\\)");
		if (number_arguments == 0) { // Without arguments, allow to use the callback without parenthesis
			pattern = "(?:" + pattern + "|" + name + ")";   << Switched order of pattern and name
		}
		return Regex{"\\s*" + pattern + "\\s*"};
	}
```

After this fix Inja works correctly on all three platforms.

**Comment by pantor** [comment]
Thanks, should be fixed with the latest commit.

**Comment by ludekvodicka** [comment]
Will you consider to add all mentioned checks to the code? It would be better to pre-initialize all values as same as check array sizes before accessing it.

**Comment by ludekvodicka** [comment]
Or should I create separated issues and describe it in more details?

**Comment by pantor** [comment]
Yeah, that would be helpful. 👍
