### ISSUE TITLE
Missign reference when passing map of regexes

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#37]
In function used for match regexes, there is missing reference so every time expression is evaluated whole map is created again.

Also in for loop, there is missing reference, so this means another copy

```
template<typename T, typename S>
inline MatchType<T> match(const std::string& input, std::map<T, Regex, S> regexes) { << Missing reference
	MatchType<T> match;
	for (const auto e : regexes) {   << Missing reference
		if (std::regex_match(input.cbegin(), input.cend(), match, e.second)) {
			match.set_type(e.first);
			match.set_regex(e.second);
			return match;
		}
	}
	return match;
}
```

This will be much faster:

```
template<typename T, typename S>
inline MatchType<T> match(const std::string& input, const std::map<T, Regex, S> &regexes) {
	MatchType<T> match;
	for (const auto &e : regexes) {
		if (std::regex_match(input.cbegin(), input.cend(), match, e.second)) {
			match.set_type(e.first);
			match.set_regex(e.second);
			return match;
		}
	}
	return match;
}
```

**Comment by ludekvodicka** [comment]
The same in search() functions

`inline Match search(const std::string& input, const Regex &regex, size_t position) {`

and

`inline MatchType<T> search(const std::string& input, const std::map<T, Regex>& regexes, size_t position) {`

also would be much better to store Regexes as pointer instead of copy in function search():

`	std::vector<Regex> regexes_vector;`

**Comment by pantor** [comment]
This is implemented in the latest commit. Thanks!
