### ISSUE TITLE
Add Inja to vcpkg

### ISSUE THREAD

**Issue by edmBernard** [pantor/inja#45]
Have you planned to add Inja to vcpkg system ?
https://github.com/Microsoft/vcpkg
or can I add it ?

**Comment by pantor** [comment]
Feel free to add it!

**Comment by edmBernard** [comment]
I create a pull request : https://github.com/Microsoft/vcpkg/pull/3428

**Comment by pantor** [comment]
Great, i've added vcpkg to the readme. Thanks!
