### ISSUE TITLE
New line handling after condition statements.

### ISSUE THREAD

**Issue by Edwinem** [pantor/inja#49]
Would it be possible to add the ability to manage whether we want a new line after a condition statement. I know Jinja has this capability via the trim blocks options or by changing the {%....%} pattern to {%....  - %}. This would tremendously help with the readability of the generated result. 

Currently 
~~~~
//Start
{% if length(classes)>0 %}
    {% for cl in classes %}
        {% if cl.is_viable %}
        //dosomething
       {% endif %}
    {% endfor %}
{% endif %}
//End
~~~~
Becomes this
~~~~
//Start



        //dosomething



//End
~~~~

And it would be nice if it could be this
~~~~
//Start
        //dosomething
//End
~~~~

**Comment by pantor** [comment]
Yep, that bothers me too.

**Comment by pantor** [comment]
For now, you can just use the line statements as
```
//Start
## if length(classes)>0
## for cl in classes
## if cl.is_viable
    //dosomething
## endif
## endfor
## endif
//End
```

**Comment by pantor** [comment]
This should be fixed with the newest commit.
