### ISSUE TITLE
Get property of last item

### ISSUE THREAD

**Issue by zippy84** [pantor/inja#57]
I have a list that looks like this

`[ { "x" : 12, "y": 8 }, { "x" : 5, "y": 19 }, { "x" : 2, "y": 0 }]`

and I want to get the value of x in the last item.

I tried this

`{{ last(data).x }}`

or

`{{ last(data).y }}`.

My program terminates with an runtime_error. What is wrong with it?

**Comment by zippy84** [comment]
Could you implement it as @flexferrum did? It is essential. Thx.

**Comment by pantor** [comment]
Ok, I'll have a look at this.

**Comment by NCDemonic** [comment]
Is there any progress on this? Unfortunatelly I'am now stuck at this issue...

**Comment by pantor** [comment]
I'll close this issue in favor of #147. Thanks for reporting!

**Comment by pantor** [comment]
This is now fixed and a test (https://github.com/pantor/inja/blob/02394683b151cdb520c8fb636f3bda77ed4f965d/test/test-functions.cpp#L268) was added.
