### ISSUE TITLE
Callback for in-memory includes?

### ISSUE THREAD

**Issue by ludekvodicka** [pantor/inja#7]
Hi there,

As first let me thanks for great work you did on Inja. It's the best of templating libraries for C++ I tried. I 'm just integrating your library to my projects and have a question.

I have a system where I need to generate several templates and then merge it into one result. Because it's not stored in FileSystem I'm doing that in memory.

Unfortunately, I didn't find an alternative for` {% include "footer.html" %}` for in-memory templates.

Would be great to have some callback where I can call {% include "identifier" } which get data from the app and put it back to generated result.

Currently, I doing that via variables `{{ templates.xxx }}` but it doesn't seem to be an optimal way because such variables can be very large.

Is there any way how to do that better? And if not, would you be so kind and add this feature?

Thanks!

**Comment by ludekvodicka** [comment]
I checked your code and it seems that there is currently no way how to handle such situation.

I prepared quick PR with callback-statement implementation. I also included few improvements in other parts of code where I received some warnings on different platforms.

https://github.com/pantor/inja/pull/8

Hope you will find it useful and include it in your version. Thanks!

**Comment by pantor** [comment]
Thanks!

Yeah, I was thinking about adding callbacks to inja as well. However I'm not sure what the best implementation for this might be, but your code looks promising! It would be great to add own functions (maybe via lambdas or std::function) to inja and use them directly in the template.

In the meantime I'll merge the other improvements and warning fixes of your PR. Thanks again!

**Comment by ludekvodicka** [comment]
You're welcome. I strongly agree that callbacks are good to go. 

Currently, I'm thinking about extending callbacks also for not-found statement values. This will also greatly improve possibilities of inja.  And as you wrote, this will allow you to add also own functions which is great too (and I will use it later for myself too ;-) ).

If you're interested, I can create another PR.

But I'm not sure about naming convention and the form for callbacks. Not sure if ICallback suits you, if not, feel free to rename it.

**Comment by ludekvodicka** [comment]
I just created new PR with following changes

- new callback for missing values. When {{xxx}} is not found it's executed callback onMissing where it is possible to pass value

- central point for throwing exceptions - because I added few new exceptions when callbacks are not handled I also added central point for all exceptions (including your original ones)

- updated callbacks to return true/false to detect if callback was proceed or not - to be able to detect if callback was handled by application, callback now returns true/false. Exception is thrown when callback isn't handled

**Comment by pantor** [comment]
Cool!

What do you think about my implementation of callbacks in [this branch](https://github.com/pantor/inja/tree/callbacks)?

**Comment by ludekvodicka** [comment]
I think it is good too. But it's not such universal like injected ICallback class.

With ICallback mechanism it's possible to implement missing statements handler, custom functions, etc. 

But if you prefer std::map<> rather than class injecting, I can modify my missing statement handler to similar std::function() form too.

**Comment by ludekvodicka** [comment]
I just checked your callback implementation and it's perfect!. Ability to pass several arguments to user-defined function is also great.

Can I ask if you're considering also add any form of my "missing-value" callback? 

After testing several attempts in my application I decided to allow users to access evaluated in-memory template in same convention like they access another data. This means to use {{ data.memoryTemplate }} convention.

And to provide this without copying data directly to json I'm currently using my "onMissingValue" handler.

Thanks

**Comment by pantor** [comment]
For now, I think a global missing-value callback would not be the most elegant implementation. Instead you can use the `default(variable, undefined-callback)` function and combine it with your own callback. Would that be ok?

**Comment by ludekvodicka** [comment]
Unfornately this would mean that users have to add default() anywhere in the template. The problem is that I need to allow users to create/edit own templates. So I'm trying to do it most user friendly.

But it's not big deal for now, I will show them error message and they will have to fix the template.

The second reason why I needed undefined callbacks was resolved via custom functions, because I used this callback to access for data not available in data json. But this is now solved via special data() calls, so this is soved too.

**Comment by flexferrum** [comment]
Hi,

I'm trying to extend inja in order to support both filesystem and in-memory templates (for the 'include' statements) now. And I'm slightly confused about this issue. The reason is following: for now inja accesses files in two way:
1. Load file as a string (Parser::load_file)
2. Load file as a stream (Environment::load_json)
Unfortunately, it's difficult to generalize this two ways. Imagine, you can handle the absence of some file. What do you want to return to inja internals? Content of the absent file? Content of which form (string or stream)? Throw exception? Try to substitute one file path with another? It's a subject to discuss.

**Comment by pantor** [comment]
I've added includes for in-memory templates with the latest commit. Feel free to share your feedback.

@flexferrum I'm not sure if I understand your problem. `Environment::load_json` returns a `json` object. You are right, there is no error handling yet and I would love to see exceptions if no file was found.

**Comment by flexferrum** [comment]
> I've added includes for in-memory templates with the latest commit. Feel free to share your feedback.

I saw. But I was thinking about more flexible solution:
https://github.com/flexferrum/inja/compare/master...flexferrum:7f5a9dc576c2cc855e01fa13526e7433db63cff6
And I've stuck on interface of template absence handler.

> I'm not sure if I understand your problem. Environment::load_json returns a json object

Yes. But it accesses file as a stream, not string. So (in my version) generic file provider should support dual interface of file reading: as a string and as a stream. And this is a question: what 'file absence' handler should return?

**Comment by pantor** [comment]
@flexferrum That looks great. If a file is missing, I think it should throw an exception. However, I'll close this issue as the main idea is implemented. Feel free to open a more specific issue or even a PR. 😉

**Comment by flexferrum** [comment]
> That looks great. If a file is missing, I think it should throw an exception. However, I'll close this issue as the main idea is implemented. Feel free to open a more specific issue or even a PR.

Ok. I'll think how to combine your approach with in-memory templates cache and mine one and then prepare the appropriate PR.
