### ISSUE TITLE
How to Original output

### ISSUE THREAD

**Issue by xmh0511** [pantor/inja#70]
such as  the template file contents are   ````<div>{{no_value}}</div>````, I want the result is ````<div>{{no_value}}</div>````,What shall I do?

**Comment by xmh0511** [comment]
but  sometimes ,I could be use some front web javascript lib ,these lib defined some syntaxs as like as inja been ,it will make parse error

**Comment by xmh0511** [comment]
but  sometimes ,I could be use some front web javascript lib ,these lib defined some syntaxs as like as inja been ,it will make parse error

**Comment by pantor** [comment]
Then you can adapt the syntax via 
```
Environment env;
env.set_expression("{&", "&}");
```
