### ISSUE TITLE
Indirection for object lookup?

### ISSUE THREAD

**Issue by abrownsword** [pantor/inja#71]
I want to do this:

{% for key in keys %}
{{key}} = {{dict.key}}
{% endfor %}

i.e. for each key in a keys array, use it to look up a value in an dictionary.  Haven't been able to figure out how to do what with existing notation.  Is it possible, or can it be added?

**Comment by pantor** [comment]
I'm sorry, this is currently not possible. However, you could use your dict directly:
```
{% for key, val in keys %}
{{ key }} = {{ val }}
{% endfor %}
```
This should be added to the Readme.

**Comment by abrownsword** [comment]
Note that in my case keys is not the same as dict.  The array "keys" is a sorted subset of the desired keys, and "dict" is a dictionary (json::object) that contains the actual <key,value> pairs.  I would actually also like to be able to pass in a dictionary that maps a subset name as a key into another dictionary that contains the available "keys" arrays (i.e.  subset -> json::array).  A popup menu on the webpage I'm generating could then select a specific subset, and use that to build the table.

For the moment I've used a custom function hardcoded to access the dictionary instead, and am evaluating whether it is better to do this functionality browser-side in javascript.  Unfortunately this is my only inja use-case currently, so <shrug>.

**Comment by mhhollomon** [comment]
I think you could do it this way:

```
{% for key, value in dict %}
  {% if key in keys %}
    {{key}} = {{value}}
  {% endif %}
{% endfor %}
```
