### ISSUE TITLE
External json files

### ISSUE THREAD

**Issue by sramsay** [pantor/inja#74]
Assuming I have a file foo.txt with this single line:

`{{ bar }}`

And I have a data.json file in the same directory like so:

`{
"bar": "example"
}`

Why would a binary compiled from this code:

```
int main() {

      inja::Environment env;

      env.write( "./foo.txt", "./data.json", "./bar.txt");

}
```

in the same directory produce:

`libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: [inja.exception.render_error] variable 'bar' not found
Abort trap: 6`

**Comment by pantor** [comment]
I'm sorry I can't reproduce this issue. As your example is very similar to the [simple file test](https://github.com/pantor/inja/tree/master/test/data/simple-file), it should work fine on the tested compilers. What is your exact setup?

**Comment by sramsay** [comment]
Thanks for the reply!  And sorry for putting this in as a bug (I assume it's not, since the whole system would probably fall over if this didn't work).

I'm on OS X, and I've tried a number of different toolchains (including Clang 7.0.1, gcc 8.2.0, and Xcode's clang), but I'm also getting the same behavior on Linux.  All produce the same error.  I have tried unsetting all CFLAGS (so there aren't any optimizations interfering).  It compiles any way I do it, but blows up even with something like:

`CPPFLAGS="" LDFLAGS="" g++-8 -I/usr/local/include -std=c++17 try.cpp`

I should mention that the inja build passes all tests.  I have nohlmann's json installed, and I've placed all headers from the include directory into /usr/local/include/inja (and then #include <inja/inja.hpp>)

I'm sure I'm doing something utterly boneheaded here, but I can't figure out what it is.

**Comment by pantor** [comment]
Ah, I'm so sorry, I've renamed some functions in v2 and forgot to update the Readme. You just need to call `env.write_with_json_file("./foo.txt", "./data.json", "./bar.txt");`

**Comment by pantor** [comment]
Additionally I should have a look if I can stop the implicit conversion from invalid json strings to the json data type.

**Comment by sramsay** [comment]
That's it!  Thank you so much.  I'll let you close this issue (I don't know if you want to keep that implicit conversion issue in this thread).

And thanks for the heroic work on tool.  It's exactly what I need.
