### ISSUE TITLE
Problem with user defined callback 

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [pantor/inja#77]
I created a callback function "setValue":

``
     env->add_callback("setValue", 2, [this](Parsed::Arguments args, json x) {

        std::string key = env->get_argument<std::string>(args, 0, x);
        std::string value = env->get_argument<std::string>(args, 1, x);
        std::cout << "setValue key: " << key << std::endl;
        std::cout << "setValue value: " << value << std::endl;
        this->values[key] = value;
        return "";
    });
``

I am trying to call it like this:
``
{{ setValue("need_comma", ", ") }}
``

However, I keep getting an error:
``
terminate called after throwing an instance of 'std::runtime_error'
  what():  [inja.exception.render_error] variable '/"need_comma", "' not found
``

How can I pass two string arguments to a callback function?

**Comment by gi9obru0etuPlc6wozls** [comment]
I made a self contained example for testing:
    #include <iostream>
    #include <nlohmann/json.hpp>
    #include <inja.hpp>

    int main() {

        nlohmann::json data;

        inja::Environment env = inja::Environment();
        env.add_callback("test", 2, [&env](inja::Parsed::Arguments args, const nlohmann::json &data) {
            std::string s1 = env.get_argument(args, 0, data);
            std::string s2 = env.get_argument(args, 1, data);

            std::string r = s1 + " & " + s2;
            return r;
        });

        std::string s1 = env.render(R"X(Test: {{ test("Ernie, ", "Bert") }})X", data);   // Works
        std::cout << "s1: " << s1 << std::endl;

        std::string s2 = env.render(R"X(Test: {{ test("Ernie", ", Bert") }})X", data);   // Throws error
        std::cout << "s2: " << s2 << std::endl;


        return 0;
    }

**Comment by mhhollomon** [comment]
I'm not sure what version of Inja you re using, but in v2.0.1, that call back should look like:

```cpp
env.add_callback("test", 2, [](Arguments& args) {
    std::string s1 args.at(0)->get<std::string>();
    std::string s2 args.at(1)->get<std::string>();

    return (s1 + " & " + s2);
});
```
