### ISSUE TITLE
Build problem By vs2015

### ISSUE THREAD

**Issue by cctvbtx** [pantor/inja#87]
Building  error if using VS2015+string-view-lite.
How to use vs2015 to be successful??
or Whether to use vs2017 can solve the problem??

**Comment by DanmerZ** [comment]
Try
```
#define nssv_CPLUSPLUS 201103L
#include <inja/inja.hpp>
```

**Comment by kzeslaf** [comment]
Updating string-view-lite to version 1.4.0 fixes VS2015 build. See: #128

**Comment by pantor** [comment]
That should be fixed with the latest commit thanks to @kzeslaf‘s PR.
