### ISSUE TITLE
Update vcpkg to latest release v2.1

### ISSUE THREAD

**Issue by semaJUni** [pantor/inja#89]
Hi,
I installed the library using vcpkg (VS2017) and some the examples result in the program crashing.

Here is some example code:
```
Environment env;
//Template temp = env.parse_template("./count.html");
json data;
// Reply with data
response_.set(http::field::content_type, "text/html");
beast::ostream(response_.body())
    << env.render("{% for i in range(4) %}{{ loop.index1 }}{% endfor %}", data);
```

It also doesn't with the following:
`{{ guests.1 }}`
where guests is an array:
`data["guests"] = {"a", "b", "c"};`
However, the following does work:
`{{ guests }}`

This code causes a crash, throwing a `variable /loop.index1 not found`  render_error exception.

Not sure if I am doing something wrong?

Thanks,
James.

**Comment by semaJUni** [comment]
Okay, after investigating further, the vcpkg seems really out of date compared to the master branch of the repository. This means the syntax doesn't match the examples.

**Comment by semaJUni** [comment]
After manually downloading the `inja.hpp` file from the v2.1 release the code works as expected. Changing title to reflect this.

**Comment by pantor** [comment]
I've opened a pull request at vcpkg to update inja to the newest version. Thanks!
