### ISSUE TITLE
Fix default for Environment global_path

### ISSUE THREAD

**Issue by jkelling** [pantor/inja#90]
The default ctor for Environment sets global_path to "./" ( environment.hpp:40 ) . Which breaks absolute paths in calls to render_file(..) or rather parse_template(..).

Breaking absolute paths is quite unexpected behavior for a default, especially because it is not documented.

I suggest to change the default to "" (empty string) this still allows relative paths and does not break absolute paths.

**Comment by pantor** [comment]
I think you're right. With the latest commit, I now changed the default path to the empty string, so it does not break absolute paths anymore.
