### ISSUE TITLE
function "length" can't apply on string ,(allway return 1).

### ISSUE THREAD

**Issue by zhuangyan-stone** [pantor/inja#92]
It is this a feature？How to get length of  string?

**Comment by Kvaz1r** [comment]
There isn't embedded length function for string but you can always define your own callback. 
For example so:

```
#include "inja.hpp"

// Just for convenience
using namespace inja;
using json = nlohmann::json;

int main()
{
    Environment env;
    json data;
    data["name"] = "world";
    env.add_callback("len", 1, [](Arguments& args)
    {
        return args.at(0)->get<std::string>().length();
    });

    std::cout<<env.render("Length for string = {{ len(name) }} \n", data);
} 
```

**Comment by pantor** [comment]
Hi @zhuangyan-stone, thanks for pointing that out, and thanks to @Kvaz1r for the possible solution! With the latest commit, the `length` function should also work with strings.
