### ISSUE TITLE
Array lookup by index

### ISSUE THREAD

**Issue by Goutte** [pantor/inja#94]
I need to access an array value by index. Is there a feature for this? If not, this is a feature request.

```twig
{% for i in range(n) %}
uniform float trail_size_{{ i }} = {{ trail_sizes[i] }};
{% endfor %}
```

I tried `trail_sizes.i` and `trail_sizes/i`. I also tried `{% for k, v in trail_sizes %}`, but it requires an object, not a list.

**Comment by Goutte** [comment]
Of course there's a workaround:

```twig
{% for trail_size in trail_sizes %}
uniform float trail_size_{{ loop.index0 }} = {{ trail_size }};
{% endfor %}
```

But I have multiple lists of the same size and the workaround is creating some clutter in the template.

**Comment by pantor** [comment]
I've added the `at` function with the latest commit, so now you can write:
```
{% for i in range(n) %}
uniform float trail_size_{{ i }} = {{ at(trail_sizes, i) }};
{% endfor %}
```
