### ISSUE TITLE
How to define 2 dimension array?

### ISSUE THREAD

**Issue by xtuer** [pantor/inja#95]
Is there any way to define a 2 dimension array?
I did as following but it prompt errors: [inja.exception.render_error] type must be array

```cpp
data["names"] = {{"Jeff-1", "Jeff-2"}, {"Seb-1", "Seb-2"}};

env.render(R"(Hello
{% for name in names %}
    {% for n in name %}
        {{ n }}
    {% endfor %}
{% endfor %}!)", data)
```

**Comment by Kvaz1r** [comment]
Declare it explicit as an array: 

```
#include "inja.hpp"

// Just for convenience
using namespace inja;
using json = nlohmann::json;

int main()
{
    json data;
    data["names"] = json::array({{"Jeff-1", "Jeff-2"}, {"Seb-1", "Seb-2"}});

    render_to(std::cout, R"(Hello
{% for name in names %}
    {% for n in name %}
        {{ n }}
    {% endfor %}
{% endfor %}!)", data);
}
```

**Comment by xtuer** [comment]
> Declare it explicit as an array:
> 
> ```
> #include "inja.hpp"
> 
> // Just for convenience
> using namespace inja;
> using json = nlohmann::json;
> 
> int main()
> {
>     json data;
>     data["names"] = json::array({{"Jeff-1", "Jeff-2"}, {"Seb-1", "Seb-2"}});
> 
>     render_to(std::cout, R"(Hello
> {% for name in names %}
>     {% for n in name %}
>         {{ n }}
>     {% endfor %}
> {% endfor %}!)", data);
> }
> ```

Thank you so much, it works!
