### ISSUE TITLE
Compiled templates

### ISSUE THREAD

**Issue by JDeuce** [pantor/inja#96]
One of the great features of jinja2 is the fact that you can process and "compile" the template a single time, in order to accelerate successive runs of the same template.  You can also compile the templates before the application even starts, so even the first run is quick.

I'm wondering if you've considered a feature like this for Inja. I'm in a scenario where I need to generate hundreds of thousands of the same template, and re-parsing it every time really adds up.

**Comment by pantor** [comment]
This should be possible with the `Template` class using the `parse` method of the inja `Environment`. You can parse a template from a string or a file first and render it later on. This way, inja does not need to reparse a file every time.

**Comment by JDeuce** [comment]
I did miss that in the docs initially and I've since tried it, but it didn't seem to offer the speedup that I was expecting - barely on the order of 5% speedup on 1k template runs, parsing vs not parsing each time.

I had in mind something that might auto-generate optimized C++ code from the template which could then be compiled with the rest of the project.

**Comment by dorfire** [comment]
@pantor, would it be possible to do the actual parsing at **compile-time**? I'd love to help with developing such a feature if it aligns with this project's goals

**Comment by pantor** [comment]
@dorfire It would align the the project's goals, but I'm unsure whether compile-time parsing is feasible with reasonable code complexity and overhead in the codebase. In general I'd prefer to keep the codebase on the smaller and more readable side.
