### ISSUE TITLE
JSON key with space

### ISSUE THREAD

**Issue by gi9obru0etuPlc6wozls** [pantor/inja#98]
If I have JSON that looks like this:
```
json data = R"(
{
	"create table": "blog"
}
)"_json;

std::string outputFileName = env->render("models/{{create table}}.cpp", data);
```
How do I access the "create table" key?

**Comment by gi9obru0etuPlc6wozls** [comment]
I have created a pull request that enables this functionality:

```
std::string outputFileName = env->render("models/{{create\ table}}.cpp", data);
```

**Comment by pantor** [comment]
For now, I'll go by the jinja template syntax which doesn't seem to allow whitespaces in variable names.
But thank you so much for your input and your PR!
